package com.iot.pojo;

public class AccountDataInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_data_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_data_info.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_data_info.basis_data_file_last_modified
     *
     * @mbggenerated
     */
    private String basis_data_file_last_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_data_info.record_data_file_last_modified
     *
     * @mbggenerated
     */
    private String record_data_file_last_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_data_info.table_dcgs_record
     *
     * @mbggenerated
     */
    private String table_dcgs_record;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_data_info.table_control_record
     *
     * @mbggenerated
     */
    private String table_control_record;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_data_info.table_sensor_record
     *
     * @mbggenerated
     */
    private String table_sensor_record;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_data_info.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    private String region_addr;

    private String group_addr;
    private String sence_adde;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_data_info.id
     *
     * @return the value of account_data_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_data_info.id
     *
     * @param id the value for account_data_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_data_info.account_id
     *
     * @return the value of account_data_info.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_data_info.account_id
     *
     * @param account_id the value for account_data_info.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_data_info.basis_data_file_last_modified
     *
     * @return the value of account_data_info.basis_data_file_last_modified
     *
     * @mbggenerated
     */
    public String getBasis_data_file_last_modified() {
        return basis_data_file_last_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_data_info.basis_data_file_last_modified
     *
     * @param basis_data_file_last_modified the value for account_data_info.basis_data_file_last_modified
     *
     * @mbggenerated
     */
    public void setBasis_data_file_last_modified(String basis_data_file_last_modified) {
        this.basis_data_file_last_modified = basis_data_file_last_modified == null ? null : basis_data_file_last_modified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_data_info.record_data_file_last_modified
     *
     * @return the value of account_data_info.record_data_file_last_modified
     *
     * @mbggenerated
     */
    public String getRecord_data_file_last_modified() {
        return record_data_file_last_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_data_info.record_data_file_last_modified
     *
     * @param record_data_file_last_modified the value for account_data_info.record_data_file_last_modified
     *
     * @mbggenerated
     */
    public void setRecord_data_file_last_modified(String record_data_file_last_modified) {
        this.record_data_file_last_modified = record_data_file_last_modified == null ? null : record_data_file_last_modified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_data_info.table_dcgs_record
     *
     * @return the value of account_data_info.table_dcgs_record
     *
     * @mbggenerated
     */
    public String getTable_dcgs_record() {
        return table_dcgs_record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_data_info.table_dcgs_record
     *
     * @param table_dcgs_record the value for account_data_info.table_dcgs_record
     *
     * @mbggenerated
     */
    public void setTable_dcgs_record(String table_dcgs_record) {
        this.table_dcgs_record = table_dcgs_record == null ? null : table_dcgs_record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_data_info.table_control_record
     *
     * @return the value of account_data_info.table_control_record
     *
     * @mbggenerated
     */
    public String getTable_control_record() {
        return table_control_record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_data_info.table_control_record
     *
     * @param table_control_record the value for account_data_info.table_control_record
     *
     * @mbggenerated
     */
    public void setTable_control_record(String table_control_record) {
        this.table_control_record = table_control_record == null ? null : table_control_record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_data_info.table_sensor_record
     *
     * @return the value of account_data_info.table_sensor_record
     *
     * @mbggenerated
     */
    public String getTable_sensor_record() {
        return table_sensor_record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_data_info.table_sensor_record
     *
     * @param table_sensor_record the value for account_data_info.table_sensor_record
     *
     * @mbggenerated
     */
    public void setTable_sensor_record(String table_sensor_record) {
        this.table_sensor_record = table_sensor_record == null ? null : table_sensor_record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_data_info.gateway_id
     *
     * @return the value of account_data_info.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_data_info.gateway_id
     *
     * @param gateway_id the value for account_data_info.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    public String getRegion_addr() {
        return region_addr;
    }

    public void setRegion_addr(String region_addr) {
        this.region_addr = region_addr;
    }

    public String getGroup_addr() {
        return group_addr;
    }

    public void setGroup_addr(String group_addr) {
        this.group_addr = group_addr;
    }

    public String getSence_adde() {
        return sence_adde;
    }

    public void setSence_adde(String sence_adde) {
        this.sence_adde = sence_adde;
    }

    @Override
    public String toString() {
        return "AccountDataInfo{" +
                "id='" + id + '\'' +
                ", account_id='" + account_id + '\'' +
                ", basis_data_file_last_modified='" + basis_data_file_last_modified + '\'' +
                ", record_data_file_last_modified='" + record_data_file_last_modified + '\'' +
                ", table_dcgs_record='" + table_dcgs_record + '\'' +
                ", table_control_record='" + table_control_record + '\'' +
                ", table_sensor_record='" + table_sensor_record + '\'' +
                ", gateway_id='" + gateway_id + '\'' +
                ", region_addr='" + region_addr + '\'' +
                ", group_addr='" + group_addr + '\'' +
                ", sence_adde='" + sence_adde + '\'' +
                '}';
    }
}