package com.iot.pojo;

import java.util.List;

/**
 * Created by adminchen on 16/6/15.
 */
public class AddGroupMembers {

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column table_group_members.id
 *
 * @mbggenerated
 */
private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.group_members_guid
     *
     * @mbggenerated
     */
    private String group_members_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.table_group_guid
     *
     * @mbggenerated
     */
    private String table_group_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.group_addr
     *
     * @mbggenerated
     */
    private String group_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.device_addr
     *
     * @mbggenerated
     */
    private String device_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.device_guid
     *
     * @mbggenerated
     */
    private String device_guid;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGroup_members_guid() {
        return group_members_guid;
    }

    public void setGroup_members_guid(String group_members_guid) {
        this.group_members_guid = group_members_guid;
    }

    public String getTable_group_guid() {
        return table_group_guid;
    }

    public void setTable_group_guid(String table_group_guid) {
        this.table_group_guid = table_group_guid;
    }

    public String getGroup_addr() {
        return group_addr;
    }

    public void setGroup_addr(String group_addr) {
        this.group_addr = group_addr;
    }

    public String getDevice_addr() {
        return device_addr;
    }

    public void setDevice_addr(String device_addr) {
        this.device_addr = device_addr;
    }

    public String getDevice_guid() {
        return device_guid;
    }

    public void setDevice_guid(String device_guid) {
        this.device_guid = device_guid;
    }

    public String getGateway_id() {
        return gateway_id;
    }

    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id;
    }

    public String getAccount_id() {
        return account_id;
    }

    public void setAccount_id(String account_id) {
        this.account_id = account_id;
    }

    public String getDevice_type() {
        return device_type;
    }

    public void setDevice_type(String device_type) {
        this.device_type = device_type;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.gateway_id
     *
     * @mbggenerated

     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.account_id
     *
     * @mbggenerated
     */
    private String  device_type;

    private String account_id;

    private String user_id;

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }
}
