package com.iot.pojo;

public class AppInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.app_name
     *
     * @mbggenerated
     */
    private String app_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.app_type
     *
     * @mbggenerated
     */
    private String app_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.app_version
     *
     * @mbggenerated
     */
    private String app_version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.app_name
     *
     * @return the value of app_info.app_name
     *
     * @mbggenerated
     */
    public String getApp_name() {
        return app_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.app_name
     *
     * @param app_name the value for app_info.app_name
     *
     * @mbggenerated
     */
    public void setApp_name(String app_name) {
        this.app_name = app_name == null ? null : app_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.app_type
     *
     * @return the value of app_info.app_type
     *
     * @mbggenerated
     */
    public String getApp_type() {
        return app_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.app_type
     *
     * @param app_type the value for app_info.app_type
     *
     * @mbggenerated
     */
    public void setApp_type(String app_type) {
        this.app_type = app_type == null ? null : app_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.app_version
     *
     * @return the value of app_info.app_version
     *
     * @mbggenerated
     */
    public String getApp_version() {
        return app_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.app_version
     *
     * @param app_version the value for app_info.app_version
     *
     * @mbggenerated
     */
    public void setApp_version(String app_version) {
        this.app_version = app_version == null ? null : app_version.trim();
    }
}