package com.iot.pojo;

public class DeviceStandard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_standard.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_standard.device_class_id
     *
     * @mbggenerated
     */
    private String device_class_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_standard.standard
     *
     * @mbggenerated
     */
    private String standard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_standard.id
     *
     * @return the value of device_standard.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_standard.id
     *
     * @param id the value for device_standard.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_standard.device_class_id
     *
     * @return the value of device_standard.device_class_id
     *
     * @mbggenerated
     */
    public String getDevice_class_id() {
        return device_class_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_standard.device_class_id
     *
     * @param device_class_id the value for device_standard.device_class_id
     *
     * @mbggenerated
     */
    public void setDevice_class_id(String device_class_id) {
        this.device_class_id = device_class_id == null ? null : device_class_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_standard.standard
     *
     * @return the value of device_standard.standard
     *
     * @mbggenerated
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_standard.standard
     *
     * @param standard the value for device_standard.standard
     *
     * @mbggenerated
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }
}