package com.iot.pojo;

public class DispatcherLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcher_location.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcher_location.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcher_location.dispatcher_gateway
     *
     * @mbggenerated
     */
    private String dispatcher_gateway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcher_location.sub_gateway
     *
     * @mbggenerated
     */
    private String sub_gateway;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatcher_location.id
     *
     * @return the value of dispatcher_location.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatcher_location.id
     *
     * @param id the value for dispatcher_location.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatcher_location.account_id
     *
     * @return the value of dispatcher_location.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatcher_location.account_id
     *
     * @param account_id the value for dispatcher_location.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatcher_location.dispatcher_gateway
     *
     * @return the value of dispatcher_location.dispatcher_gateway
     *
     * @mbggenerated
     */
    public String getDispatcher_gateway() {
        return dispatcher_gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatcher_location.dispatcher_gateway
     *
     * @param dispatcher_gateway the value for dispatcher_location.dispatcher_gateway
     *
     * @mbggenerated
     */
    public void setDispatcher_gateway(String dispatcher_gateway) {
        this.dispatcher_gateway = dispatcher_gateway == null ? null : dispatcher_gateway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatcher_location.sub_gateway
     *
     * @return the value of dispatcher_location.sub_gateway
     *
     * @mbggenerated
     */
    public String getSub_gateway() {
        return sub_gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatcher_location.sub_gateway
     *
     * @param sub_gateway the value for dispatcher_location.sub_gateway
     *
     * @mbggenerated
     */
    public void setSub_gateway(String sub_gateway) {
        this.sub_gateway = sub_gateway == null ? null : sub_gateway.trim();
    }
}