package com.iot.pojo;

public class PrivateRecipeIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_recipe_index.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_recipe_index.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_recipe_index.region_guid
     *
     * @mbggenerated
     */
    private String region_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_recipe_index.private_recipe_id
     *
     * @mbggenerated
     */
    private String private_recipe_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_recipe_index.index
     *
     * @mbggenerated
     */
    private String seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_recipe_index.start_time
     *
     * @mbggenerated
     */
    private String start_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_recipe_index.id
     *
     * @return the value of private_recipe_index.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_recipe_index.id
     *
     * @param id the value for private_recipe_index.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_recipe_index.account_id
     *
     * @return the value of private_recipe_index.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_recipe_index.account_id
     *
     * @param account_id the value for private_recipe_index.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_recipe_index.region_guid
     *
     * @return the value of private_recipe_index.region_guid
     *
     * @mbggenerated
     */
    public String getRegion_guid() {
        return region_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_recipe_index.region_guid
     *
     * @param region_guid the value for private_recipe_index.region_guid
     *
     * @mbggenerated
     */
    public void setRegion_guid(String region_guid) {
        this.region_guid = region_guid == null ? null : region_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_recipe_index.private_recipe_id
     *
     * @return the value of private_recipe_index.private_recipe_id
     *
     * @mbggenerated
     */
    public String getPrivate_recipe_id() {
        return private_recipe_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_recipe_index.private_recipe_id
     *
     * @param private_recipe_id the value for private_recipe_index.private_recipe_id
     *
     * @mbggenerated
     */
    public void setPrivate_recipe_id(String private_recipe_id) {
        this.private_recipe_id = private_recipe_id == null ? null : private_recipe_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_recipe_index.index
     *
     * @return the value of private_recipe_index.index
     *
     * @mbggenerated
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_recipe_index.index
     *
     * @param index the value for private_recipe_index.index
     *
     * @mbggenerated
     */
    public void setSeq(String index) {
        this.seq = index == null ? null : index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_recipe_index.start_time
     *
     * @return the value of private_recipe_index.start_time
     *
     * @mbggenerated
     */
    public String getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_recipe_index.start_time
     *
     * @param start_time the value for private_recipe_index.start_time
     *
     * @mbggenerated
     */
    public void setStart_time(String start_time) {
        this.start_time = start_time == null ? null : start_time.trim();
    }

    private String status;

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}