package com.iot.pojo;

public class PrivateRecipeDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_recipe_data.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_recipe_data.reserve05
     *
     * @mbggenerated
     */
    private String reserve05;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_recipe_data.id
     *
     * @return the value of private_recipe_data.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_recipe_data.id
     *
     * @param id the value for private_recipe_data.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_recipe_data.reserve05
     *
     * @return the value of private_recipe_data.reserve05
     *
     * @mbggenerated
     */
    public String getReserve05() {
        return reserve05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_recipe_data.reserve05
     *
     * @param reserve05 the value for private_recipe_data.reserve05
     *
     * @mbggenerated
     */
    public void setReserve05(String reserve05) {
        this.reserve05 = reserve05 == null ? null : reserve05.trim();
    }
}