package com.iot.pojo;

public class PublicRecipe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe.public_recipe_id
     *
     * @mbggenerated
     */
    private String public_recipe_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe.crop_name
     *
     * @mbggenerated
     */
    private String crop_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe.public_recipe_id
     *
     * @return the value of public_recipe.public_recipe_id
     *
     * @mbggenerated
     */
    public String getPublic_recipe_id() {
        return public_recipe_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe.public_recipe_id
     *
     * @param public_recipe_id the value for public_recipe.public_recipe_id
     *
     * @mbggenerated
     */
    public void setPublic_recipe_id(String public_recipe_id) {
        this.public_recipe_id = public_recipe_id == null ? null : public_recipe_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe.crop_name
     *
     * @return the value of public_recipe.crop_name
     *
     * @mbggenerated
     */
    public String getCrop_name() {
        return crop_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe.crop_name
     *
     * @param crop_name the value for public_recipe.crop_name
     *
     * @mbggenerated
     */
    public void setCrop_name(String crop_name) {
        this.crop_name = crop_name == null ? null : crop_name.trim();
    }
}