package com.iot.pojo;

public class PublicRecipeData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.public_recipe_id
     *
     * @mbggenerated
     */
    private String public_recipe_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.day
     *
     * @mbggenerated
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.start_time
     *
     * @mbggenerated
     */
    private String start_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.end_time
     *
     * @mbggenerated
     */
    private String end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.channel_combination
     *
     * @mbggenerated
     */
    private String channel_combination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.reserve03
     *
     * @mbggenerated
     */
    private String reserve03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.reserve04
     *
     * @mbggenerated
     */
    private String reserve04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.reserve05
     *
     * @mbggenerated
     */
    private String reserve05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.reserve06
     *
     * @mbggenerated
     */
    private String reserve06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.reserve07
     *
     * @mbggenerated
     */
    private String reserve07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.create_time
     *
     * @mbggenerated
     */
    private String create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_PH_start
     *
     * @mbggenerated
     */
    private String substrate_PH_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_PH_end
     *
     * @mbggenerated
     */
    private String substrate_PH_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_Conductivity_start
     *
     * @mbggenerated
     */
    private String substrate_Conductivity_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_Conductivity_end
     *
     * @mbggenerated
     */
    private String substrate_Conductivity_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_Temperature_start
     *
     * @mbggenerated
     */
    private String substrate_Temperature_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_Temperature_end
     *
     * @mbggenerated
     */
    private String substrate_Temperature_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.ppfd_start
     *
     * @mbggenerated
     */
    private String ppfd_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.ppfd_end
     *
     * @mbggenerated
     */
    private String ppfd_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.liquid_PH_start
     *
     * @mbggenerated
     */
    private String liquid_PH_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.liquid_PH_end
     *
     * @mbggenerated
     */
    private String liquid_PH_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_Humidity_start
     *
     * @mbggenerated
     */
    private String substrate_Humidity_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_Humidity_end
     *
     * @mbggenerated
     */
    private String substrate_Humidity_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.liquid_DOC_start
     *
     * @mbggenerated
     */
    private String liquid_DOC_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.liquid_DOC_end
     *
     * @mbggenerated
     */
    private String liquid_DOC_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.liquid_Conductivity_start
     *
     * @mbggenerated
     */
    private String liquid_Conductivity_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.liquid_Conductivity_end
     *
     * @mbggenerated
     */
    private String liquid_Conductivity_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_DOC_start
     *
     * @mbggenerated
     */
    private String substrate_DOC_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.substrate_DOC_end
     *
     * @mbggenerated
     */
    private String substrate_DOC_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.lai_start
     *
     * @mbggenerated
     */
    private String lai_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.lai_end
     *
     * @mbggenerated
     */
    private String lai_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.carbon_Dioxide_start
     *
     * @mbggenerated
     */
    private String carbon_Dioxide_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.carbon_Dioxide_end
     *
     * @mbggenerated
     */
    private String carbon_Dioxide_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.illuminance_start
     *
     * @mbggenerated
     */
    private String illuminance_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.illuminance_end
     *
     * @mbggenerated
     */
    private String illuminance_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.air_Temperature_start
     *
     * @mbggenerated
     */
    private String air_Temperature_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.air_Temperature_end
     *
     * @mbggenerated
     */
    private String air_Temperature_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.air_Humidity_start
     *
     * @mbggenerated
     */
    private String air_Humidity_start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_recipe_data.air_Humidity_end
     *
     * @mbggenerated
     */
    private String air_Humidity_end;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.id
     *
     * @return the value of public_recipe_data.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.id
     *
     * @param id the value for public_recipe_data.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.public_recipe_id
     *
     * @return the value of public_recipe_data.public_recipe_id
     *
     * @mbggenerated
     */
    public String getPublic_recipe_id() {
        return public_recipe_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.public_recipe_id
     *
     * @param public_recipe_id the value for public_recipe_data.public_recipe_id
     *
     * @mbggenerated
     */
    public void setPublic_recipe_id(String public_recipe_id) {
        this.public_recipe_id = public_recipe_id == null ? null : public_recipe_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.day
     *
     * @return the value of public_recipe_data.day
     *
     * @mbggenerated
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.day
     *
     * @param day the value for public_recipe_data.day
     *
     * @mbggenerated
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.start_time
     *
     * @return the value of public_recipe_data.start_time
     *
     * @mbggenerated
     */
    public String getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.start_time
     *
     * @param start_time the value for public_recipe_data.start_time
     *
     * @mbggenerated
     */
    public void setStart_time(String start_time) {
        this.start_time = start_time == null ? null : start_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.end_time
     *
     * @return the value of public_recipe_data.end_time
     *
     * @mbggenerated
     */
    public String getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.end_time
     *
     * @param end_time the value for public_recipe_data.end_time
     *
     * @mbggenerated
     */
    public void setEnd_time(String end_time) {
        this.end_time = end_time == null ? null : end_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.channel_combination
     *
     * @return the value of public_recipe_data.channel_combination
     *
     * @mbggenerated
     */
    public String getChannel_combination() {
        return channel_combination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.channel_combination
     *
     * @param channel_combination the value for public_recipe_data.channel_combination
     *
     * @mbggenerated
     */
    public void setChannel_combination(String channel_combination) {
        this.channel_combination = channel_combination == null ? null : channel_combination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.reserve03
     *
     * @return the value of public_recipe_data.reserve03
     *
     * @mbggenerated
     */
    public String getReserve03() {
        return reserve03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.reserve03
     *
     * @param reserve03 the value for public_recipe_data.reserve03
     *
     * @mbggenerated
     */
    public void setReserve03(String reserve03) {
        this.reserve03 = reserve03 == null ? null : reserve03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.reserve04
     *
     * @return the value of public_recipe_data.reserve04
     *
     * @mbggenerated
     */
    public String getReserve04() {
        return reserve04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.reserve04
     *
     * @param reserve04 the value for public_recipe_data.reserve04
     *
     * @mbggenerated
     */
    public void setReserve04(String reserve04) {
        this.reserve04 = reserve04 == null ? null : reserve04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.reserve05
     *
     * @return the value of public_recipe_data.reserve05
     *
     * @mbggenerated
     */
    public String getReserve05() {
        return reserve05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.reserve05
     *
     * @param reserve05 the value for public_recipe_data.reserve05
     *
     * @mbggenerated
     */
    public void setReserve05(String reserve05) {
        this.reserve05 = reserve05 == null ? null : reserve05.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.reserve06
     *
     * @return the value of public_recipe_data.reserve06
     *
     * @mbggenerated
     */
    public String getReserve06() {
        return reserve06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.reserve06
     *
     * @param reserve06 the value for public_recipe_data.reserve06
     *
     * @mbggenerated
     */
    public void setReserve06(String reserve06) {
        this.reserve06 = reserve06 == null ? null : reserve06.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.reserve07
     *
     * @return the value of public_recipe_data.reserve07
     *
     * @mbggenerated
     */
    public String getReserve07() {
        return reserve07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.reserve07
     *
     * @param reserve07 the value for public_recipe_data.reserve07
     *
     * @mbggenerated
     */
    public void setReserve07(String reserve07) {
        this.reserve07 = reserve07 == null ? null : reserve07.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.create_time
     *
     * @return the value of public_recipe_data.create_time
     *
     * @mbggenerated
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.create_time
     *
     * @param create_time the value for public_recipe_data.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_PH_start
     *
     * @return the value of public_recipe_data.substrate_PH_start
     *
     * @mbggenerated
     */
    public String getSubstrate_PH_start() {
        return substrate_PH_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_PH_start
     *
     * @param substrate_PH_start the value for public_recipe_data.substrate_PH_start
     *
     * @mbggenerated
     */
    public void setSubstrate_PH_start(String substrate_PH_start) {
        this.substrate_PH_start = substrate_PH_start == null ? null : substrate_PH_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_PH_end
     *
     * @return the value of public_recipe_data.substrate_PH_end
     *
     * @mbggenerated
     */
    public String getSubstrate_PH_end() {
        return substrate_PH_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_PH_end
     *
     * @param substrate_PH_end the value for public_recipe_data.substrate_PH_end
     *
     * @mbggenerated
     */
    public void setSubstrate_PH_end(String substrate_PH_end) {
        this.substrate_PH_end = substrate_PH_end == null ? null : substrate_PH_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_Conductivity_start
     *
     * @return the value of public_recipe_data.substrate_Conductivity_start
     *
     * @mbggenerated
     */
    public String getSubstrate_Conductivity_start() {
        return substrate_Conductivity_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_Conductivity_start
     *
     * @param substrate_Conductivity_start the value for public_recipe_data.substrate_Conductivity_start
     *
     * @mbggenerated
     */
    public void setSubstrate_Conductivity_start(String substrate_Conductivity_start) {
        this.substrate_Conductivity_start = substrate_Conductivity_start == null ? null : substrate_Conductivity_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_Conductivity_end
     *
     * @return the value of public_recipe_data.substrate_Conductivity_end
     *
     * @mbggenerated
     */
    public String getSubstrate_Conductivity_end() {
        return substrate_Conductivity_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_Conductivity_end
     *
     * @param substrate_Conductivity_end the value for public_recipe_data.substrate_Conductivity_end
     *
     * @mbggenerated
     */
    public void setSubstrate_Conductivity_end(String substrate_Conductivity_end) {
        this.substrate_Conductivity_end = substrate_Conductivity_end == null ? null : substrate_Conductivity_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_Temperature_start
     *
     * @return the value of public_recipe_data.substrate_Temperature_start
     *
     * @mbggenerated
     */
    public String getSubstrate_Temperature_start() {
        return substrate_Temperature_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_Temperature_start
     *
     * @param substrate_Temperature_start the value for public_recipe_data.substrate_Temperature_start
     *
     * @mbggenerated
     */
    public void setSubstrate_Temperature_start(String substrate_Temperature_start) {
        this.substrate_Temperature_start = substrate_Temperature_start == null ? null : substrate_Temperature_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_Temperature_end
     *
     * @return the value of public_recipe_data.substrate_Temperature_end
     *
     * @mbggenerated
     */
    public String getSubstrate_Temperature_end() {
        return substrate_Temperature_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_Temperature_end
     *
     * @param substrate_Temperature_end the value for public_recipe_data.substrate_Temperature_end
     *
     * @mbggenerated
     */
    public void setSubstrate_Temperature_end(String substrate_Temperature_end) {
        this.substrate_Temperature_end = substrate_Temperature_end == null ? null : substrate_Temperature_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.ppfd_start
     *
     * @return the value of public_recipe_data.ppfd_start
     *
     * @mbggenerated
     */
    public String getPpfd_start() {
        return ppfd_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.ppfd_start
     *
     * @param ppfd_start the value for public_recipe_data.ppfd_start
     *
     * @mbggenerated
     */
    public void setPpfd_start(String ppfd_start) {
        this.ppfd_start = ppfd_start == null ? null : ppfd_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.ppfd_end
     *
     * @return the value of public_recipe_data.ppfd_end
     *
     * @mbggenerated
     */
    public String getPpfd_end() {
        return ppfd_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.ppfd_end
     *
     * @param ppfd_end the value for public_recipe_data.ppfd_end
     *
     * @mbggenerated
     */
    public void setPpfd_end(String ppfd_end) {
        this.ppfd_end = ppfd_end == null ? null : ppfd_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.liquid_PH_start
     *
     * @return the value of public_recipe_data.liquid_PH_start
     *
     * @mbggenerated
     */
    public String getLiquid_PH_start() {
        return liquid_PH_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.liquid_PH_start
     *
     * @param liquid_PH_start the value for public_recipe_data.liquid_PH_start
     *
     * @mbggenerated
     */
    public void setLiquid_PH_start(String liquid_PH_start) {
        this.liquid_PH_start = liquid_PH_start == null ? null : liquid_PH_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.liquid_PH_end
     *
     * @return the value of public_recipe_data.liquid_PH_end
     *
     * @mbggenerated
     */
    public String getLiquid_PH_end() {
        return liquid_PH_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.liquid_PH_end
     *
     * @param liquid_PH_end the value for public_recipe_data.liquid_PH_end
     *
     * @mbggenerated
     */
    public void setLiquid_PH_end(String liquid_PH_end) {
        this.liquid_PH_end = liquid_PH_end == null ? null : liquid_PH_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_Humidity_start
     *
     * @return the value of public_recipe_data.substrate_Humidity_start
     *
     * @mbggenerated
     */
    public String getSubstrate_Humidity_start() {
        return substrate_Humidity_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_Humidity_start
     *
     * @param substrate_Humidity_start the value for public_recipe_data.substrate_Humidity_start
     *
     * @mbggenerated
     */
    public void setSubstrate_Humidity_start(String substrate_Humidity_start) {
        this.substrate_Humidity_start = substrate_Humidity_start == null ? null : substrate_Humidity_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_Humidity_end
     *
     * @return the value of public_recipe_data.substrate_Humidity_end
     *
     * @mbggenerated
     */
    public String getSubstrate_Humidity_end() {
        return substrate_Humidity_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_Humidity_end
     *
     * @param substrate_Humidity_end the value for public_recipe_data.substrate_Humidity_end
     *
     * @mbggenerated
     */
    public void setSubstrate_Humidity_end(String substrate_Humidity_end) {
        this.substrate_Humidity_end = substrate_Humidity_end == null ? null : substrate_Humidity_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.liquid_DOC_start
     *
     * @return the value of public_recipe_data.liquid_DOC_start
     *
     * @mbggenerated
     */
    public String getLiquid_DOC_start() {
        return liquid_DOC_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.liquid_DOC_start
     *
     * @param liquid_DOC_start the value for public_recipe_data.liquid_DOC_start
     *
     * @mbggenerated
     */
    public void setLiquid_DOC_start(String liquid_DOC_start) {
        this.liquid_DOC_start = liquid_DOC_start == null ? null : liquid_DOC_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.liquid_DOC_end
     *
     * @return the value of public_recipe_data.liquid_DOC_end
     *
     * @mbggenerated
     */
    public String getLiquid_DOC_end() {
        return liquid_DOC_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.liquid_DOC_end
     *
     * @param liquid_DOC_end the value for public_recipe_data.liquid_DOC_end
     *
     * @mbggenerated
     */
    public void setLiquid_DOC_end(String liquid_DOC_end) {
        this.liquid_DOC_end = liquid_DOC_end == null ? null : liquid_DOC_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.liquid_Conductivity_start
     *
     * @return the value of public_recipe_data.liquid_Conductivity_start
     *
     * @mbggenerated
     */
    public String getLiquid_Conductivity_start() {
        return liquid_Conductivity_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.liquid_Conductivity_start
     *
     * @param liquid_Conductivity_start the value for public_recipe_data.liquid_Conductivity_start
     *
     * @mbggenerated
     */
    public void setLiquid_Conductivity_start(String liquid_Conductivity_start) {
        this.liquid_Conductivity_start = liquid_Conductivity_start == null ? null : liquid_Conductivity_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.liquid_Conductivity_end
     *
     * @return the value of public_recipe_data.liquid_Conductivity_end
     *
     * @mbggenerated
     */
    public String getLiquid_Conductivity_end() {
        return liquid_Conductivity_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.liquid_Conductivity_end
     *
     * @param liquid_Conductivity_end the value for public_recipe_data.liquid_Conductivity_end
     *
     * @mbggenerated
     */
    public void setLiquid_Conductivity_end(String liquid_Conductivity_end) {
        this.liquid_Conductivity_end = liquid_Conductivity_end == null ? null : liquid_Conductivity_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_DOC_start
     *
     * @return the value of public_recipe_data.substrate_DOC_start
     *
     * @mbggenerated
     */
    public String getSubstrate_DOC_start() {
        return substrate_DOC_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_DOC_start
     *
     * @param substrate_DOC_start the value for public_recipe_data.substrate_DOC_start
     *
     * @mbggenerated
     */
    public void setSubstrate_DOC_start(String substrate_DOC_start) {
        this.substrate_DOC_start = substrate_DOC_start == null ? null : substrate_DOC_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.substrate_DOC_end
     *
     * @return the value of public_recipe_data.substrate_DOC_end
     *
     * @mbggenerated
     */
    public String getSubstrate_DOC_end() {
        return substrate_DOC_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.substrate_DOC_end
     *
     * @param substrate_DOC_end the value for public_recipe_data.substrate_DOC_end
     *
     * @mbggenerated
     */
    public void setSubstrate_DOC_end(String substrate_DOC_end) {
        this.substrate_DOC_end = substrate_DOC_end == null ? null : substrate_DOC_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.lai_start
     *
     * @return the value of public_recipe_data.lai_start
     *
     * @mbggenerated
     */
    public String getLai_start() {
        return lai_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.lai_start
     *
     * @param lai_start the value for public_recipe_data.lai_start
     *
     * @mbggenerated
     */
    public void setLai_start(String lai_start) {
        this.lai_start = lai_start == null ? null : lai_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.lai_end
     *
     * @return the value of public_recipe_data.lai_end
     *
     * @mbggenerated
     */
    public String getLai_end() {
        return lai_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.lai_end
     *
     * @param lai_end the value for public_recipe_data.lai_end
     *
     * @mbggenerated
     */
    public void setLai_end(String lai_end) {
        this.lai_end = lai_end == null ? null : lai_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.carbon_Dioxide_start
     *
     * @return the value of public_recipe_data.carbon_Dioxide_start
     *
     * @mbggenerated
     */
    public String getCarbon_Dioxide_start() {
        return carbon_Dioxide_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.carbon_Dioxide_start
     *
     * @param carbon_Dioxide_start the value for public_recipe_data.carbon_Dioxide_start
     *
     * @mbggenerated
     */
    public void setCarbon_Dioxide_start(String carbon_Dioxide_start) {
        this.carbon_Dioxide_start = carbon_Dioxide_start == null ? null : carbon_Dioxide_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.carbon_Dioxide_end
     *
     * @return the value of public_recipe_data.carbon_Dioxide_end
     *
     * @mbggenerated
     */
    public String getCarbon_Dioxide_end() {
        return carbon_Dioxide_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.carbon_Dioxide_end
     *
     * @param carbon_Dioxide_end the value for public_recipe_data.carbon_Dioxide_end
     *
     * @mbggenerated
     */
    public void setCarbon_Dioxide_end(String carbon_Dioxide_end) {
        this.carbon_Dioxide_end = carbon_Dioxide_end == null ? null : carbon_Dioxide_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.illuminance_start
     *
     * @return the value of public_recipe_data.illuminance_start
     *
     * @mbggenerated
     */
    public String getIlluminance_start() {
        return illuminance_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.illuminance_start
     *
     * @param illuminance_start the value for public_recipe_data.illuminance_start
     *
     * @mbggenerated
     */
    public void setIlluminance_start(String illuminance_start) {
        this.illuminance_start = illuminance_start == null ? null : illuminance_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.illuminance_end
     *
     * @return the value of public_recipe_data.illuminance_end
     *
     * @mbggenerated
     */
    public String getIlluminance_end() {
        return illuminance_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.illuminance_end
     *
     * @param illuminance_end the value for public_recipe_data.illuminance_end
     *
     * @mbggenerated
     */
    public void setIlluminance_end(String illuminance_end) {
        this.illuminance_end = illuminance_end == null ? null : illuminance_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.air_Temperature_start
     *
     * @return the value of public_recipe_data.air_Temperature_start
     *
     * @mbggenerated
     */
    public String getAir_Temperature_start() {
        return air_Temperature_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.air_Temperature_start
     *
     * @param air_Temperature_start the value for public_recipe_data.air_Temperature_start
     *
     * @mbggenerated
     */
    public void setAir_Temperature_start(String air_Temperature_start) {
        this.air_Temperature_start = air_Temperature_start == null ? null : air_Temperature_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.air_Temperature_end
     *
     * @return the value of public_recipe_data.air_Temperature_end
     *
     * @mbggenerated
     */
    public String getAir_Temperature_end() {
        return air_Temperature_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.air_Temperature_end
     *
     * @param air_Temperature_end the value for public_recipe_data.air_Temperature_end
     *
     * @mbggenerated
     */
    public void setAir_Temperature_end(String air_Temperature_end) {
        this.air_Temperature_end = air_Temperature_end == null ? null : air_Temperature_end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.air_Humidity_start
     *
     * @return the value of public_recipe_data.air_Humidity_start
     *
     * @mbggenerated
     */
    public String getAir_Humidity_start() {
        return air_Humidity_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.air_Humidity_start
     *
     * @param air_Humidity_start the value for public_recipe_data.air_Humidity_start
     *
     * @mbggenerated
     */
    public void setAir_Humidity_start(String air_Humidity_start) {
        this.air_Humidity_start = air_Humidity_start == null ? null : air_Humidity_start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_recipe_data.air_Humidity_end
     *
     * @return the value of public_recipe_data.air_Humidity_end
     *
     * @mbggenerated
     */
    public String getAir_Humidity_end() {
        return air_Humidity_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_recipe_data.air_Humidity_end
     *
     * @param air_Humidity_end the value for public_recipe_data.air_Humidity_end
     *
     * @mbggenerated
     */
    public void setAir_Humidity_end(String air_Humidity_end) {
        this.air_Humidity_end = air_Humidity_end == null ? null : air_Humidity_end.trim();
    }
}