package com.iot.pojo;

public class RegionStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_status.region_guid
     *
     * @mbggenerated
     */
    private String region_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region_status.region_status
     *
     * @mbggenerated
     */
    private String region_status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_status.region_guid
     *
     * @return the value of region_status.region_guid
     *
     * @mbggenerated
     */
    public String getRegion_guid() {
        return region_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_status.region_guid
     *
     * @param region_guid the value for region_status.region_guid
     *
     * @mbggenerated
     */
    public void setRegion_guid(String region_guid) {
        this.region_guid = region_guid == null ? null : region_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region_status.region_status
     *
     * @return the value of region_status.region_status
     *
     * @mbggenerated
     */
    public String getRegion_status() {
        return region_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region_status.region_status
     *
     * @param region_status the value for region_status.region_status
     *
     * @mbggenerated
     */
    public void setRegion_status(String region_status) {
        this.region_status = region_status == null ? null : region_status.trim();
    }
}