package com.iot.pojo;

public class TableSceneMembers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.scene_members_guid
     *
     * @mbggenerated
     */
    private String scene_members_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.table_scene_guid
     *
     * @mbggenerated
     */
    private String table_scene_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.scene_addr
     *
     * @mbggenerated
     */
    private String scene_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.device_addr
     *
     * @mbggenerated
     */
    private String device_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.device_value
     *
     * @mbggenerated
     */
    private String device_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.device_delay
     *
     * @mbggenerated
     */
    private String device_delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.device_guid
     *
     * @mbggenerated
     */
    private String device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene_members.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.id
     *
     * @return the value of table_scene_members.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.id
     *
     * @param id the value for table_scene_members.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.scene_members_guid
     *
     * @return the value of table_scene_members.scene_members_guid
     *
     * @mbggenerated
     */
    public String getScene_members_guid() {
        return scene_members_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.scene_members_guid
     *
     * @param scene_members_guid the value for table_scene_members.scene_members_guid
     *
     * @mbggenerated
     */
    public void setScene_members_guid(String scene_members_guid) {
        this.scene_members_guid = scene_members_guid == null ? null : scene_members_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.table_scene_guid
     *
     * @return the value of table_scene_members.table_scene_guid
     *
     * @mbggenerated
     */
    public String getTable_scene_guid() {
        return table_scene_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.table_scene_guid
     *
     * @param table_scene_guid the value for table_scene_members.table_scene_guid
     *
     * @mbggenerated
     */
    public void setTable_scene_guid(String table_scene_guid) {
        this.table_scene_guid = table_scene_guid == null ? null : table_scene_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.scene_addr
     *
     * @return the value of table_scene_members.scene_addr
     *
     * @mbggenerated
     */
    public String getscene_addr() {
        return scene_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.scene_addr
     *
     * @param scene_addr the value for table_scene_members.scene_addr
     *
     * @mbggenerated
     */
    public void setscene_addr(String scene_addr) {
        this.scene_addr = scene_addr == null ? null : scene_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.device_addr
     *
     * @return the value of table_scene_members.device_addr
     *
     * @mbggenerated
     */
    public String getDevice_addr() {
        return device_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.device_addr
     *
     * @param device_addr the value for table_scene_members.device_addr
     *
     * @mbggenerated
     */
    public void setDevice_addr(String device_addr) {
        this.device_addr = device_addr == null ? null : device_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.device_value
     *
     * @return the value of table_scene_members.device_value
     *
     * @mbggenerated
     */
    public String getDevice_value() {
        return device_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.device_value
     *
     * @param device_value the value for table_scene_members.device_value
     *
     * @mbggenerated
     */
    public void setDevice_value(String device_value) {
        this.device_value = device_value == null ? null : device_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.device_delay
     *
     * @return the value of table_scene_members.device_delay
     *
     * @mbggenerated
     */
    public String getDevice_delay() {
        return device_delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.device_delay
     *
     * @param device_delay the value for table_scene_members.device_delay
     *
     * @mbggenerated
     */
    public void setDevice_delay(String device_delay) {
        this.device_delay = device_delay == null ? null : device_delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.device_guid
     *
     * @return the value of table_scene_members.device_guid
     *
     * @mbggenerated
     */
    public String getDevice_guid() {
        return device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.device_guid
     *
     * @param device_guid the value for table_scene_members.device_guid
     *
     * @mbggenerated
     */
    public void setDevice_guid(String device_guid) {
        this.device_guid = device_guid == null ? null : device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.gateway_id
     *
     * @return the value of table_scene_members.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.gateway_id
     *
     * @param gateway_id the value for table_scene_members.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene_members.account_id
     *
     * @return the value of table_scene_members.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene_members.account_id
     *
     * @param account_id the value for table_scene_members.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    private String device_name;

    public String getDevice_name() {
        return device_name;
    }

    public void setDevice_name(String device_name) {
        this.device_name = device_name;
    }
}