package com.iot.pojo;

public class TableRegister {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_register.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_register.register_guid
     *
     * @mbggenerated
     */
    private String register_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_register.table_device_guid
     *
     * @mbggenerated
     */
    private String table_device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_register.device_register_type
     *
     * @mbggenerated
     */
    private String device_register_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_register.register_name
     *
     * @mbggenerated
     */
    private String register_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_register.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_register.id
     *
     * @return the value of table_register.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_register.id
     *
     * @param id the value for table_register.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_register.register_guid
     *
     * @return the value of table_register.register_guid
     *
     * @mbggenerated
     */
    public String getRegister_guid() {
        return register_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_register.register_guid
     *
     * @param register_guid the value for table_register.register_guid
     *
     * @mbggenerated
     */
    public void setRegister_guid(String register_guid) {
        this.register_guid = register_guid == null ? null : register_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_register.table_device_guid
     *
     * @return the value of table_register.table_device_guid
     *
     * @mbggenerated
     */
    public String getTable_device_guid() {
        return table_device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_register.table_device_guid
     *
     * @param table_device_guid the value for table_register.table_device_guid
     *
     * @mbggenerated
     */
    public void setTable_device_guid(String table_device_guid) {
        this.table_device_guid = table_device_guid == null ? null : table_device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_register.device_register_type
     *
     * @return the value of table_register.device_register_type
     *
     * @mbggenerated
     */
    public String getDevice_register_type() {
        return device_register_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_register.device_register_type
     *
     * @param device_register_type the value for table_register.device_register_type
     *
     * @mbggenerated
     */
    public void setDevice_register_type(String device_register_type) {
        this.device_register_type = device_register_type == null ? null : device_register_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_register.register_name
     *
     * @return the value of table_register.register_name
     *
     * @mbggenerated
     */
    public String getRegister_name() {
        return register_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_register.register_name
     *
     * @param register_name the value for table_register.register_name
     *
     * @mbggenerated
     */
    public void setRegister_name(String register_name) {
        this.register_name = register_name == null ? null : register_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_register.account_id
     *
     * @return the value of table_register.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_register.account_id
     *
     * @param account_id the value for table_register.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}