package com.iot.pojo;

public class TableConditons {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.conditions_guid
     *
     * @mbggenerated
     */
    private String conditions_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.cdts_list_guid
     *
     * @mbggenerated
     */
    private String cdts_list_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.table_device_guid
     *
     * @mbggenerated
     */
    private String table_device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.channel_bit_num
     *
     * @mbggenerated
     */
    private String channel_bit_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.compare_val
     *
     * @mbggenerated
     */
    private String compare_val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.offset_val
     *
     * @mbggenerated
     */
    private String offset_val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_conditons.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.id
     *
     * @return the value of table_conditons.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.id
     *
     * @param id the value for table_conditons.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.conditions_guid
     *
     * @return the value of table_conditons.conditions_guid
     *
     * @mbggenerated
     */
    public String getConditions_guid() {
        return conditions_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.conditions_guid
     *
     * @param conditions_guid the value for table_conditons.conditions_guid
     *
     * @mbggenerated
     */
    public void setConditions_guid(String conditions_guid) {
        this.conditions_guid = conditions_guid == null ? null : conditions_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.cdts_list_guid
     *
     * @return the value of table_conditons.cdts_list_guid
     *
     * @mbggenerated
     */
    public String getCdts_list_guid() {
        return cdts_list_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.cdts_list_guid
     *
     * @param cdts_list_guid the value for table_conditons.cdts_list_guid
     *
     * @mbggenerated
     */
    public void setCdts_list_guid(String cdts_list_guid) {
        this.cdts_list_guid = cdts_list_guid == null ? null : cdts_list_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.table_device_guid
     *
     * @return the value of table_conditons.table_device_guid
     *
     * @mbggenerated
     */
    public String getTable_device_guid() {
        return table_device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.table_device_guid
     *
     * @param table_device_guid the value for table_conditons.table_device_guid
     *
     * @mbggenerated
     */
    public void setTable_device_guid(String table_device_guid) {
        this.table_device_guid = table_device_guid == null ? null : table_device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.gateway_id
     *
     * @return the value of table_conditons.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.gateway_id
     *
     * @param gateway_id the value for table_conditons.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.channel_bit_num
     *
     * @return the value of table_conditons.channel_bit_num
     *
     * @mbggenerated
     */
    public String getChannel_bit_num() {
        return channel_bit_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.channel_bit_num
     *
     * @param channel_bit_num the value for table_conditons.channel_bit_num
     *
     * @mbggenerated
     */
    public void setChannel_bit_num(String channel_bit_num) {
        this.channel_bit_num = channel_bit_num == null ? null : channel_bit_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.compare_val
     *
     * @return the value of table_conditons.compare_val
     *
     * @mbggenerated
     */
    public String getCompare_val() {
        return compare_val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.compare_val
     *
     * @param compare_val the value for table_conditons.compare_val
     *
     * @mbggenerated
     */
    public void setCompare_val(String compare_val) {
        this.compare_val = compare_val == null ? null : compare_val.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.offset_val
     *
     * @return the value of table_conditons.offset_val
     *
     * @mbggenerated
     */
    public String getOffset_val() {
        return offset_val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.offset_val
     *
     * @param offset_val the value for table_conditons.offset_val
     *
     * @mbggenerated
     */
    public void setOffset_val(String offset_val) {
        this.offset_val = offset_val == null ? null : offset_val.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_conditons.account_id
     *
     * @return the value of table_conditons.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_conditons.account_id
     *
     * @param account_id the value for table_conditons.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}