package com.iot.pojo;

public class TableGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.group_guid
     *
     * @mbggenerated
     */
    private String group_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.group_addr
     *
     * @mbggenerated
     */
    private String group_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.group_name
     *
     * @mbggenerated
     */
    private String group_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.group_switch
     *
     * @mbggenerated
     */
    private String group_switch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.group_value
     *
     * @mbggenerated
     */
    private String group_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.group_delay
     *
     * @mbggenerated
     */
    private String group_delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.id
     *
     * @return the value of table_group.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.id
     *
     * @param id the value for table_group.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.group_guid
     *
     * @return the value of table_group.group_guid
     *
     * @mbggenerated
     */
    public String getGroup_guid() {
        return group_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.group_guid
     *
     * @param group_guid the value for table_group.group_guid
     *
     * @mbggenerated
     */
    public void setGroup_guid(String group_guid) {
        this.group_guid = group_guid == null ? null : group_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.gateway_id
     *
     * @return the value of table_group.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.gateway_id
     *
     * @param gateway_id the value for table_group.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.group_addr
     *
     * @return the value of table_group.group_addr
     *
     * @mbggenerated
     */
    public String getGroup_addr() {
        return group_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.group_addr
     *
     * @param group_addr the value for table_group.group_addr
     *
     * @mbggenerated
     */
    public void setGroup_addr(String group_addr) {
        this.group_addr = group_addr == null ? null : group_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.group_name
     *
     * @return the value of table_group.group_name
     *
     * @mbggenerated
     */
    public String getGroup_name() {
        return group_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.group_name
     *
     * @param group_name the value for table_group.group_name
     *
     * @mbggenerated
     */
    public void setGroup_name(String group_name) {
        this.group_name = group_name == null ? null : group_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.group_switch
     *
     * @return the value of table_group.group_switch
     *
     * @mbggenerated
     */
    public String getGroup_switch() {
        return group_switch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.group_switch
     *
     * @param group_switch the value for table_group.group_switch
     *
     * @mbggenerated
     */
    public void setGroup_switch(String group_switch) {
        this.group_switch = group_switch == null ? null : group_switch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.group_value
     *
     * @return the value of table_group.group_value
     *
     * @mbggenerated
     */
    public String getGroup_value() {
        return group_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.group_value
     *
     * @param group_value the value for table_group.group_value
     *
     * @mbggenerated
     */
    public void setGroup_value(String group_value) {
        this.group_value = group_value == null ? null : group_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.group_delay
     *
     * @return the value of table_group.group_delay
     *
     * @mbggenerated
     */
    public String getGroup_delay() {
        return group_delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.group_delay
     *
     * @param group_delay the value for table_group.group_delay
     *
     * @mbggenerated
     */
    public void setGroup_delay(String group_delay) {
        this.group_delay = group_delay == null ? null : group_delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group.account_id
     *
     * @return the value of table_group.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group.account_id
     *
     * @param account_id the value for table_group.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    @Override
    public String toString() {
        return "TableGroup{" +
                "id='" + id + '\'' +
                ", group_guid='" + group_guid + '\'' +
                ", gateway_id='" + gateway_id + '\'' +
                ", group_addr='" + group_addr + '\'' +
                ", group_name='" + group_name + '\'' +
                ", group_switch='" + group_switch + '\'' +
                ", group_value='" + group_value + '\'' +
                ", group_delay='" + group_delay + '\'' +
                ", account_id='" + account_id + '\'' +
                '}';
    }



}