package com.iot.pojo;

public class TableGroupMembers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.group_members_guid
     *
     * @mbggenerated
     */
    private String group_members_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.table_group_guid
     *
     * @mbggenerated
     */
    private String table_group_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.group_addr
     *
     * @mbggenerated
     */
    private String group_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.device_addr
     *
     * @mbggenerated
     */
    private String device_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.device_guid
     *
     * @mbggenerated
     */
    private String device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_group_members.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group_members.id
     *
     * @return the value of table_group_members.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group_members.id
     *
     * @param id the value for table_group_members.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group_members.group_members_guid
     *
     * @return the value of table_group_members.group_members_guid
     *
     * @mbggenerated
     */
    public String getGroup_members_guid() {
        return group_members_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group_members.group_members_guid
     *
     * @param group_members_guid the value for table_group_members.group_members_guid
     *
     * @mbggenerated
     */
    public void setGroup_members_guid(String group_members_guid) {
        this.group_members_guid = group_members_guid == null ? null : group_members_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group_members.table_group_guid
     *
     * @return the value of table_group_members.table_group_guid
     *
     * @mbggenerated
     */
    public String getTable_group_guid() {
        return table_group_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group_members.table_group_guid
     *
     * @param table_group_guid the value for table_group_members.table_group_guid
     *
     * @mbggenerated
     */
    public void setTable_group_guid(String table_group_guid) {
        this.table_group_guid = table_group_guid == null ? null : table_group_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group_members.group_addr
     *
     * @return the value of table_group_members.group_addr
     *
     * @mbggenerated
     */
    public String getGroup_addr() {
        return group_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group_members.group_addr
     *
     * @param group_addr the value for table_group_members.group_addr
     *
     * @mbggenerated
     */
    public void setGroup_addr(String group_addr) {
        this.group_addr = group_addr == null ? null : group_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group_members.device_addr
     *
     * @return the value of table_group_members.device_addr
     *
     * @mbggenerated
     */
    public String getDevice_addr() {
        return device_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group_members.device_addr
     *
     * @param device_addr the value for table_group_members.device_addr
     *
     * @mbggenerated
     */
    public void setDevice_addr(String device_addr) {
        this.device_addr = device_addr == null ? null : device_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group_members.device_guid
     *
     * @return the value of table_group_members.device_guid
     *
     * @mbggenerated
     */
    public String getDevice_guid() {
        return device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group_members.device_guid
     *
     * @param device_guid the value for table_group_members.device_guid
     *
     * @mbggenerated
     */
    public void setDevice_guid(String device_guid) {
        this.device_guid = device_guid == null ? null : device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group_members.gateway_id
     *
     * @return the value of table_group_members.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group_members.gateway_id
     *
     * @param gateway_id the value for table_group_members.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_group_members.account_id
     *
     * @return the value of table_group_members.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_group_members.account_id
     *
     * @param account_id the value for table_group_members.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    public String getDevice_name() {
        return device_name;
    }

    public void setDevice_name(String device_name) {
        this.device_name = device_name;
    }

    private String device_name;
}