package com.iot.pojo;

public class TableControlRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control_record.record_guid
     *
     * @mbggenerated
     */
    private String record_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control_record.table_main_guid
     *
     * @mbggenerated
     */
    private String table_main_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control_record.table_main_name
     *
     * @mbggenerated
     */
    private String table_main_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control_record.record_time
     *
     * @mbggenerated
     */
    private String record_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control_record.switch_value
     *
     * @mbggenerated
     */
    private String switch_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control_record.delay
     *
     * @mbggenerated
     */
    private String delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control_record.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control_record.id
     *
     * @return the value of table_control_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control_record.id
     *
     * @param id the value for table_control_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control_record.record_guid
     *
     * @return the value of table_control_record.record_guid
     *
     * @mbggenerated
     */
    public String getRecord_guid() {
        return record_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control_record.record_guid
     *
     * @param record_guid the value for table_control_record.record_guid
     *
     * @mbggenerated
     */
    public void setRecord_guid(String record_guid) {
        this.record_guid = record_guid == null ? null : record_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control_record.table_main_guid
     *
     * @return the value of table_control_record.table_main_guid
     *
     * @mbggenerated
     */
    public String getTable_main_guid() {
        return table_main_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control_record.table_main_guid
     *
     * @param table_main_guid the value for table_control_record.table_main_guid
     *
     * @mbggenerated
     */
    public void setTable_main_guid(String table_main_guid) {
        this.table_main_guid = table_main_guid == null ? null : table_main_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control_record.table_main_name
     *
     * @return the value of table_control_record.table_main_name
     *
     * @mbggenerated
     */
    public String getTable_main_name() {
        return table_main_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control_record.table_main_name
     *
     * @param table_main_name the value for table_control_record.table_main_name
     *
     * @mbggenerated
     */
    public void setTable_main_name(String table_main_name) {
        this.table_main_name = table_main_name == null ? null : table_main_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control_record.record_time
     *
     * @return the value of table_control_record.record_time
     *
     * @mbggenerated
     */
    public String getRecord_time() {
        return record_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control_record.record_time
     *
     * @param record_time the value for table_control_record.record_time
     *
     * @mbggenerated
     */
    public void setRecord_time(String record_time) {
        this.record_time = record_time == null ? null : record_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control_record.switch_value
     *
     * @return the value of table_control_record.switch_value
     *
     * @mbggenerated
     */
    public String getSwitch_value() {
        return switch_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control_record.switch_value
     *
     * @param switch_value the value for table_control_record.switch_value
     *
     * @mbggenerated
     */
    public void setSwitch_value(String switch_value) {
        this.switch_value = switch_value == null ? null : switch_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control_record.delay
     *
     * @return the value of table_control_record.delay
     *
     * @mbggenerated
     */
    public String getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control_record.delay
     *
     * @param delay the value for table_control_record.delay
     *
     * @mbggenerated
     */
    public void setDelay(String delay) {
        this.delay = delay == null ? null : delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control_record.account_id
     *
     * @return the value of table_control_record.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control_record.account_id
     *
     * @param account_id the value for table_control_record.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}