package com.iot.pojo;

public class TableRegionGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_group.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_group.region_group_guid
     *
     * @mbggenerated
     */
    private String region_group_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_group.region_guid
     *
     * @mbggenerated
     */
    private String region_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_group.table_group_guid
     *
     * @mbggenerated
     */
    private String table_group_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_group.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_group.group_addr
     *
     * @mbggenerated
     */
    private String group_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_group.group_name
     *
     * @mbggenerated
     */
    private String group_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_group.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_group.id
     *
     * @return the value of table_region_group.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_group.id
     *
     * @param id the value for table_region_group.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_group.region_group_guid
     *
     * @return the value of table_region_group.region_group_guid
     *
     * @mbggenerated
     */
    public String getRegion_group_guid() {
        return region_group_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_group.region_group_guid
     *
     * @param region_group_guid the value for table_region_group.region_group_guid
     *
     * @mbggenerated
     */
    public void setRegion_group_guid(String region_group_guid) {
        this.region_group_guid = region_group_guid == null ? null : region_group_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_group.region_guid
     *
     * @return the value of table_region_group.region_guid
     *
     * @mbggenerated
     */
    public String getRegion_guid() {
        return region_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_group.region_guid
     *
     * @param region_guid the value for table_region_group.region_guid
     *
     * @mbggenerated
     */
    public void setRegion_guid(String region_guid) {
        this.region_guid = region_guid == null ? null : region_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_group.table_group_guid
     *
     * @return the value of table_region_group.table_group_guid
     *
     * @mbggenerated
     */
    public String getTable_group_guid() {
        return table_group_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_group.table_group_guid
     *
     * @param table_group_guid the value for table_region_group.table_group_guid
     *
     * @mbggenerated
     */
    public void setTable_group_guid(String table_group_guid) {
        this.table_group_guid = table_group_guid == null ? null : table_group_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_group.gateway_id
     *
     * @return the value of table_region_group.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_group.gateway_id
     *
     * @param gateway_id the value for table_region_group.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_group.group_addr
     *
     * @return the value of table_region_group.group_addr
     *
     * @mbggenerated
     */
    public String getGroup_addr() {
        return group_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_group.group_addr
     *
     * @param group_addr the value for table_region_group.group_addr
     *
     * @mbggenerated
     */
    public void setGroup_addr(String group_addr) {
        this.group_addr = group_addr == null ? null : group_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_group.group_name
     *
     * @return the value of table_region_group.group_name
     *
     * @mbggenerated
     */
    public String getGroup_name() {
        return group_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_group.group_name
     *
     * @param group_name the value for table_region_group.group_name
     *
     * @mbggenerated
     */
    public void setGroup_name(String group_name) {
        this.group_name = group_name == null ? null : group_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_group.account_id
     *
     * @return the value of table_region_group.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_group.account_id
     *
     * @param account_id the value for table_region_group.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    @Override
    public String toString() {
        return "TableRegionGroup{" +
                "id='" + id + '\'' +
                ", region_group_guid='" + region_group_guid + '\'' +
                ", region_guid='" + region_guid + '\'' +
                ", table_group_guid='" + table_group_guid + '\'' +
                ", gateway_id='" + gateway_id + '\'' +
                ", group_addr='" + group_addr + '\'' +
                ", group_name='" + group_name + '\'' +
                ", account_id='" + account_id + '\'' +
                '}';
    }
}