package com.iot.pojo;

public class TableDcgsRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.dcgs_record_guid
     *
     * @mbggenerated
     */
    private String dcgs_record_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.region_dcgs_guid
     *
     * @mbggenerated
     */
    private String region_dcgs_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.region_name
     *
     * @mbggenerated
     */
    private String region_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.dcgs_name
     *
     * @mbggenerated
     */
    private String dcgs_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.dcgs_value
     *
     * @mbggenerated
     */
    private String dcgs_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.dcgs_delay
     *
     * @mbggenerated
     */
    private String dcgs_delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.record_time
     *
     * @mbggenerated
     */
    private String record_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dcgs_record.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.id
     *
     * @return the value of table_dcgs_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.id
     *
     * @param id the value for table_dcgs_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.dcgs_record_guid
     *
     * @return the value of table_dcgs_record.dcgs_record_guid
     *
     * @mbggenerated
     */
    public String getDcgs_record_guid() {
        return dcgs_record_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.dcgs_record_guid
     *
     * @param dcgs_record_guid the value for table_dcgs_record.dcgs_record_guid
     *
     * @mbggenerated
     */
    public void setDcgs_record_guid(String dcgs_record_guid) {
        this.dcgs_record_guid = dcgs_record_guid == null ? null : dcgs_record_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.region_dcgs_guid
     *
     * @return the value of table_dcgs_record.region_dcgs_guid
     *
     * @mbggenerated
     */
    public String getRegion_dcgs_guid() {
        return region_dcgs_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.region_dcgs_guid
     *
     * @param region_dcgs_guid the value for table_dcgs_record.region_dcgs_guid
     *
     * @mbggenerated
     */
    public void setRegion_dcgs_guid(String region_dcgs_guid) {
        this.region_dcgs_guid = region_dcgs_guid == null ? null : region_dcgs_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.region_name
     *
     * @return the value of table_dcgs_record.region_name
     *
     * @mbggenerated
     */
    public String getRegion_name() {
        return region_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.region_name
     *
     * @param region_name the value for table_dcgs_record.region_name
     *
     * @mbggenerated
     */
    public void setRegion_name(String region_name) {
        this.region_name = region_name == null ? null : region_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.dcgs_name
     *
     * @return the value of table_dcgs_record.dcgs_name
     *
     * @mbggenerated
     */
    public String getDcgs_name() {
        return dcgs_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.dcgs_name
     *
     * @param dcgs_name the value for table_dcgs_record.dcgs_name
     *
     * @mbggenerated
     */
    public void setDcgs_name(String dcgs_name) {
        this.dcgs_name = dcgs_name == null ? null : dcgs_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.dcgs_value
     *
     * @return the value of table_dcgs_record.dcgs_value
     *
     * @mbggenerated
     */
    public String getDcgs_value() {
        return dcgs_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.dcgs_value
     *
     * @param dcgs_value the value for table_dcgs_record.dcgs_value
     *
     * @mbggenerated
     */
    public void setDcgs_value(String dcgs_value) {
        this.dcgs_value = dcgs_value == null ? null : dcgs_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.dcgs_delay
     *
     * @return the value of table_dcgs_record.dcgs_delay
     *
     * @mbggenerated
     */
    public String getDcgs_delay() {
        return dcgs_delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.dcgs_delay
     *
     * @param dcgs_delay the value for table_dcgs_record.dcgs_delay
     *
     * @mbggenerated
     */
    public void setDcgs_delay(String dcgs_delay) {
        this.dcgs_delay = dcgs_delay == null ? null : dcgs_delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.record_time
     *
     * @return the value of table_dcgs_record.record_time
     *
     * @mbggenerated
     */
    public String getRecord_time() {
        return record_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.record_time
     *
     * @param record_time the value for table_dcgs_record.record_time
     *
     * @mbggenerated
     */
    public void setRecord_time(String record_time) {
        this.record_time = record_time == null ? null : record_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dcgs_record.account_id
     *
     * @return the value of table_dcgs_record.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dcgs_record.account_id
     *
     * @param account_id the value for table_dcgs_record.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}