package com.iot.pojo;

public class TableScene {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene.scene_guid
     *
     * @mbggenerated
     */
    private String scene_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene.scene_addr
     *
     * @mbggenerated
     */
    private String scene_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene.scene_name
     *
     * @mbggenerated
     */
    private String scene_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene.scene_switch
     *
     * @mbggenerated
     */
    private String scene_switch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_scene.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene.id
     *
     * @return the value of table_scene.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene.id
     *
     * @param id the value for table_scene.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene.scene_guid
     *
     * @return the value of table_scene.scene_guid
     *
     * @mbggenerated
     */
    public String getScene_guid() {
        return scene_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene.scene_guid
     *
     * @param scene_guid the value for table_scene.scene_guid
     *
     * @mbggenerated
     */
    public void setScene_guid(String scene_guid) {
        this.scene_guid = scene_guid == null ? null : scene_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene.gateway_id
     *
     * @return the value of table_scene.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene.gateway_id
     *
     * @param gateway_id the value for table_scene.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene.scene_addr
     *
     * @return the value of table_scene.scene_addr
     *
     * @mbggenerated
     */
    public String getScene_addr() {
        return scene_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene.scene_addr
     *
     * @param scene_addr the value for table_scene.scene_addr
     *
     * @mbggenerated
     */
    public void setScene_addr(String scene_addr) {
        this.scene_addr = scene_addr == null ? null : scene_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene.scene_name
     *
     * @return the value of table_scene.scene_name
     *
     * @mbggenerated
     */
    public String getScene_name() {
        return scene_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene.scene_name
     *
     * @param scene_name the value for table_scene.scene_name
     *
     * @mbggenerated
     */
    public void setScene_name(String scene_name) {
        this.scene_name = scene_name == null ? null : scene_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene.scene_switch
     *
     * @return the value of table_scene.scene_switch
     *
     * @mbggenerated
     */
    public String getScene_switch() {
        return scene_switch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene.scene_switch
     *
     * @param scene_switch the value for table_scene.scene_switch
     *
     * @mbggenerated
     */
    public void setScene_switch(String scene_switch) {
        this.scene_switch = scene_switch == null ? null : scene_switch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_scene.account_id
     *
     * @return the value of table_scene.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_scene.account_id
     *
     * @param account_id the value for table_scene.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}