package com.iot.pojo;

public class TableChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.channel_guid
     *
     * @mbggenerated
     */
    private String channel_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.table_device_guid
     *
     * @mbggenerated
     */
    private String table_device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.device_name
     *
     * @mbggenerated
     */
    private String device_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.channel_class
     *
     * @mbggenerated
     */
    private String channel_class;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.channel_number
     *
     * @mbggenerated
     */
    private String channel_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.channel_name
     *
     * @mbggenerated
     */
    private String channel_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.channel_type
     *
     * @mbggenerated
     */
    private String channel_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.channel_bit_num
     *
     * @mbggenerated
     */
    private String channel_bit_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.channel_in_out
     *
     * @mbggenerated
     */
    private String channel_in_out;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_channel.account_id
     *
     * @mbggenerated
     */
    private String account_id;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.id
     *
     * @return the value of table_channel.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.id
     *
     * @param id the value for table_channel.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.channel_guid
     *
     * @return the value of table_channel.channel_guid
     *
     * @mbggenerated
     */
    public String getChannel_guid() {
        return channel_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.channel_guid
     *
     * @param channel_guid the value for table_channel.channel_guid
     *
     * @mbggenerated
     */
    public void setChannel_guid(String channel_guid) {
        this.channel_guid = channel_guid == null ? null : channel_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.table_device_guid
     *
     * @return the value of table_channel.table_device_guid
     *
     * @mbggenerated
     */
    public String getTable_device_guid() {
        return table_device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.table_device_guid
     *
     * @param table_device_guid the value for table_channel.table_device_guid
     *
     * @mbggenerated
     */
    public void setTable_device_guid(String table_device_guid) {
        this.table_device_guid = table_device_guid == null ? null : table_device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.device_name
     *
     * @return the value of table_channel.device_name
     *
     * @mbggenerated
     */
    public String getDevice_name() {
        return device_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.device_name
     *
     * @param device_name the value for table_channel.device_name
     *
     * @mbggenerated
     */
    public void setDevice_name(String device_name) {
        this.device_name = device_name == null ? null : device_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.channel_class
     *
     * @return the value of table_channel.channel_class
     *
     * @mbggenerated
     */
    public String getChannel_class() {
        return channel_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.channel_class
     *
     * @param channel_class the value for table_channel.channel_class
     *
     * @mbggenerated
     */
    public void setChannel_class(String channel_class) {
        this.channel_class = channel_class == null ? null : channel_class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.channel_number
     *
     * @return the value of table_channel.channel_number
     *
     * @mbggenerated
     */
    public String getChannel_number() {
        return channel_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.channel_number
     *
     * @param channel_number the value for table_channel.channel_number
     *
     * @mbggenerated
     */
    public void setChannel_number(String channel_number) {
        this.channel_number = channel_number == null ? null : channel_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.channel_name
     *
     * @return the value of table_channel.channel_name
     *
     * @mbggenerated
     */
    public String getChannel_name() {
        return channel_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.channel_name
     *
     * @param channel_name the value for table_channel.channel_name
     *
     * @mbggenerated
     */
    public void setChannel_name(String channel_name) {
        this.channel_name = channel_name == null ? null : channel_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.channel_type
     *
     * @return the value of table_channel.channel_type
     *
     * @mbggenerated
     */
    public String getChannel_type() {
        return channel_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.channel_type
     *
     * @param channel_type the value for table_channel.channel_type
     *
     * @mbggenerated
     */
    public void setChannel_type(String channel_type) {
        this.channel_type = channel_type == null ? null : channel_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.channel_bit_num
     *
     * @return the value of table_channel.channel_bit_num
     *
     * @mbggenerated
     */
    public String getChannel_bit_num() {
        return channel_bit_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.channel_bit_num
     *
     * @param channel_bit_num the value for table_channel.channel_bit_num
     *
     * @mbggenerated
     */
    public void setChannel_bit_num(String channel_bit_num) {
        this.channel_bit_num = channel_bit_num == null ? null : channel_bit_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.channel_in_out
     *
     * @return the value of table_channel.channel_in_out
     *
     * @mbggenerated
     */
    public String getChannel_in_out() {
        return channel_in_out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.channel_in_out
     *
     * @param channel_in_out the value for table_channel.channel_in_out
     *
     * @mbggenerated
     */
    public void setChannel_in_out(String channel_in_out) {
        this.channel_in_out = channel_in_out == null ? null : channel_in_out.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_channel.account_id
     *
     * @return the value of table_channel.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_channel.account_id
     *
     * @param account_id the value for table_channel.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    private String gateway_id;

    public String getGateway_id() {
        return gateway_id;
    }

    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id;
    }

    private String device_value;
    private String channel_value;

    public String getChannel_value() {
        return channel_value;
    }

    public void setChannel_value(String channel_value) {
        this.channel_value = channel_value;
    }

    public String getDevice_value() {
        return device_value;
    }

    public void setDevice_value(String device_value) {
        this.device_value = device_value;
    }


    @Override
    public String toString() {
        return "TableChannel{" +
                "id='" + id + '\'' +
                ", channel_guid='" + channel_guid + '\'' +
                ", table_device_guid='" + table_device_guid + '\'' +
                ", device_name='" + device_name + '\'' +
                ", channel_class='" + channel_class + '\'' +
                ", channel_number='" + channel_number + '\'' +
                ", channel_name='" + channel_name + '\'' +
                ", channel_type='" + channel_type + '\'' +
                ", channel_bit_num='" + channel_bit_num + '\'' +
                ", channel_in_out='" + channel_in_out + '\'' +
                ", account_id='" + account_id + '\'' +
                ", gateway_id='" + gateway_id + '\'' +
                ", device_value='" + device_value + '\'' +
                ", channel_value='" + channel_value + '\'' +
                '}';
    }
}