package com.iot.pojo;

import org.springframework.stereotype.Component;

@Component
public class TableDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_guid
     *
     * @mbggenerated
     */
    private String device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_addr
     *
     * @mbggenerated
     */
    private String device_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_name
     *
     * @mbggenerated
     */
    private String device_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_id
     *
     * @mbggenerated
     */
    private String device_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_type
     *
     * @mbggenerated
     */
    private String device_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_valid
     *
     * @mbggenerated
     */
    private String device_valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_switch
     *
     * @mbggenerated
     */
    private String device_switch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_value
     *
     * @mbggenerated
     */
    private String device_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_delay
     *
     * @mbggenerated
     */
    private String device_delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.device_register_type
     *
     * @mbggenerated
     */
    private String device_register_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_device.region_bunding
     *
     * @mbggenerated
     */
    private String region_bunding;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.id
     *
     * @return the value of table_device.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.id
     *
     * @param id the value for table_device.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_guid
     *
     * @return the value of table_device.device_guid
     *
     * @mbggenerated
     */
    public String getDevice_guid() {
        return device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_guid
     *
     * @param device_guid the value for table_device.device_guid
     *
     * @mbggenerated
     */
    public void setDevice_guid(String device_guid) {
        this.device_guid = device_guid == null ? null : device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.gateway_id
     *
     * @return the value of table_device.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.gateway_id
     *
     * @param gateway_id the value for table_device.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_addr
     *
     * @return the value of table_device.device_addr
     *
     * @mbggenerated
     */
    public String getDevice_addr() {
        return device_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_addr
     *
     * @param device_addr the value for table_device.device_addr
     *
     * @mbggenerated
     */
    public void setDevice_addr(String device_addr) {
        this.device_addr = device_addr == null ? null : device_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_name
     *
     * @return the value of table_device.device_name
     *
     * @mbggenerated
     */
    public String getDevice_name() {
        return device_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_name
     *
     * @param device_name the value for table_device.device_name
     *
     * @mbggenerated
     */
    public void setDevice_name(String device_name) {
        this.device_name = device_name == null ? null : device_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_id
     *
     * @return the value of table_device.device_id
     *
     * @mbggenerated
     */
    public String getDevice_id() {
        return device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_id
     *
     * @param device_id the value for table_device.device_id
     *
     * @mbggenerated
     */
    public void setDevice_id(String device_id) {
        this.device_id = device_id == null ? null : device_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_type
     *
     * @return the value of table_device.device_type
     *
     * @mbggenerated
     */
    public String getDevice_type() {
        return device_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_type
     *
     * @param device_type the value for table_device.device_type
     *
     * @mbggenerated
     */
    public void setDevice_type(String device_type) {
        this.device_type = device_type == null ? null : device_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_valid
     *
     * @return the value of table_device.device_valid
     *
     * @mbggenerated
     */
    public String getDevice_valid() {
        return device_valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_valid
     *
     * @param device_valid the value for table_device.device_valid
     *
     * @mbggenerated
     */
    public void setDevice_valid(String device_valid) {
        this.device_valid = device_valid == null ? null : device_valid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_switch
     *
     * @return the value of table_device.device_switch
     *
     * @mbggenerated
     */
    public String getDevice_switch() {
        return device_switch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_switch
     *
     * @param device_switch the value for table_device.device_switch
     *
     * @mbggenerated
     */
    public void setDevice_switch(String device_switch) {
        this.device_switch = device_switch == null ? null : device_switch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_value
     *
     * @return the value of table_device.device_value
     *
     * @mbggenerated
     */
    public String getDevice_value() {
        return device_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_value
     *
     * @param device_value the value for table_device.device_value
     *
     * @mbggenerated
     */
    public void setDevice_value(String device_value) {
        this.device_value = device_value == null ? null : device_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_delay
     *
     * @return the value of table_device.device_delay
     *
     * @mbggenerated
     */
    public String getDevice_delay() {
        return device_delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_delay
     *
     * @param device_delay the value for table_device.device_delay
     *
     * @mbggenerated
     */
    public void setDevice_delay(String device_delay) {
        this.device_delay = device_delay == null ? null : device_delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.device_register_type
     *
     * @return the value of table_device.device_register_type
     *
     * @mbggenerated
     */
    public String getDevice_register_type() {
        return device_register_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.device_register_type
     *
     * @param device_register_type the value for table_device.device_register_type
     *
     * @mbggenerated
     */
    public void setDevice_register_type(String device_register_type) {
        this.device_register_type = device_register_type == null ? null : device_register_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.account_id
     *
     * @return the value of table_device.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.account_id
     *
     * @param account_id the value for table_device.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_device.region_bunding
     *
     * @return the value of table_device.region_bunding
     *
     * @mbggenerated
     */
    public String getRegion_bunding() {
        return region_bunding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_device.region_bunding
     *
     * @param region_bunding the value for table_device.region_bunding
     *
     * @mbggenerated
     */
    public void setRegion_bunding(String region_bunding) {
        this.region_bunding = region_bunding == null ? null : region_bunding.trim();
    }
}