package com.iot.pojo;

public class TableCdtsList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_cdts_list.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_cdts_list.cdts_list_guid
     *
     * @mbggenerated
     */
    private String cdts_list_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_cdts_list.cdts_name
     *
     * @mbggenerated
     */
    private String cdts_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_cdts_list.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_cdts_list.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_cdts_list.id
     *
     * @return the value of table_cdts_list.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_cdts_list.id
     *
     * @param id the value for table_cdts_list.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_cdts_list.cdts_list_guid
     *
     * @return the value of table_cdts_list.cdts_list_guid
     *
     * @mbggenerated
     */
    public String getCdts_list_guid() {
        return cdts_list_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_cdts_list.cdts_list_guid
     *
     * @param cdts_list_guid the value for table_cdts_list.cdts_list_guid
     *
     * @mbggenerated
     */
    public void setCdts_list_guid(String cdts_list_guid) {
        this.cdts_list_guid = cdts_list_guid == null ? null : cdts_list_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_cdts_list.cdts_name
     *
     * @return the value of table_cdts_list.cdts_name
     *
     * @mbggenerated
     */
    public String getCdts_name() {
        return cdts_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_cdts_list.cdts_name
     *
     * @param cdts_name the value for table_cdts_list.cdts_name
     *
     * @mbggenerated
     */
    public void setCdts_name(String cdts_name) {
        this.cdts_name = cdts_name == null ? null : cdts_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_cdts_list.gateway_id
     *
     * @return the value of table_cdts_list.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_cdts_list.gateway_id
     *
     * @param gateway_id the value for table_cdts_list.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_cdts_list.account_id
     *
     * @return the value of table_cdts_list.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_cdts_list.account_id
     *
     * @param account_id the value for table_cdts_list.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}