package com.iot.pojo;

public class TableRegionDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.region_device_guid
     *
     * @mbggenerated
     */
    private String region_device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.region_guid
     *
     * @mbggenerated
     */
    private String region_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.region_addr
     *
     * @mbggenerated
     */
    private String region_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.region_name
     *
     * @mbggenerated
     */
    private String region_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.table_device_guid
     *
     * @mbggenerated
     */
    private String table_device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.device_addr
     *
     * @mbggenerated
     */
    private String device_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.device_name
     *
     * @mbggenerated
     */
    private String device_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.channel_class
     *
     * @mbggenerated
     */
    private String channel_class;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.channel_guid
     *
     * @mbggenerated
     */
    private String channel_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.channel_name
     *
     * @mbggenerated
     */
    private String channel_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.channel_type
     *
     * @mbggenerated
     */
    private String channel_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.channel_bit_num
     *
     * @mbggenerated
     */
    private String channel_bit_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region_device.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.id
     *
     * @return the value of table_region_device.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.id
     *
     * @param id the value for table_region_device.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.region_device_guid
     *
     * @return the value of table_region_device.region_device_guid
     *
     * @mbggenerated
     */
    public String getRegion_device_guid() {
        return region_device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.region_device_guid
     *
     * @param region_device_guid the value for table_region_device.region_device_guid
     *
     * @mbggenerated
     */
    public void setRegion_device_guid(String region_device_guid) {
        this.region_device_guid = region_device_guid == null ? null : region_device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.region_guid
     *
     * @return the value of table_region_device.region_guid
     *
     * @mbggenerated
     */
    public String getRegion_guid() {
        return region_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.region_guid
     *
     * @param region_guid the value for table_region_device.region_guid
     *
     * @mbggenerated
     */
    public void setRegion_guid(String region_guid) {
        this.region_guid = region_guid == null ? null : region_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.region_addr
     *
     * @return the value of table_region_device.region_addr
     *
     * @mbggenerated
     */
    public String getRegion_addr() {
        return region_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.region_addr
     *
     * @param region_addr the value for table_region_device.region_addr
     *
     * @mbggenerated
     */
    public void setRegion_addr(String region_addr) {
        this.region_addr = region_addr == null ? null : region_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.region_name
     *
     * @return the value of table_region_device.region_name
     *
     * @mbggenerated
     */
    public String getRegion_name() {
        return region_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.region_name
     *
     * @param region_name the value for table_region_device.region_name
     *
     * @mbggenerated
     */
    public void setRegion_name(String region_name) {
        this.region_name = region_name == null ? null : region_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.table_device_guid
     *
     * @return the value of table_region_device.table_device_guid
     *
     * @mbggenerated
     */
    public String getTable_device_guid() {
        return table_device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.table_device_guid
     *
     * @param table_device_guid the value for table_region_device.table_device_guid
     *
     * @mbggenerated
     */
    public void setTable_device_guid(String table_device_guid) {
        this.table_device_guid = table_device_guid == null ? null : table_device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.gateway_id
     *
     * @return the value of table_region_device.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.gateway_id
     *
     * @param gateway_id the value for table_region_device.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.device_addr
     *
     * @return the value of table_region_device.device_addr
     *
     * @mbggenerated
     */
    public String getDevice_addr() {
        return device_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.device_addr
     *
     * @param device_addr the value for table_region_device.device_addr
     *
     * @mbggenerated
     */
    public void setDevice_addr(String device_addr) {
        this.device_addr = device_addr == null ? null : device_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.device_name
     *
     * @return the value of table_region_device.device_name
     *
     * @mbggenerated
     */
    public String getDevice_name() {
        return device_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.device_name
     *
     * @param device_name the value for table_region_device.device_name
     *
     * @mbggenerated
     */
    public void setDevice_name(String device_name) {
        this.device_name = device_name == null ? null : device_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.channel_class
     *
     * @return the value of table_region_device.channel_class
     *
     * @mbggenerated
     */
    public String getChannel_class() {
        return channel_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.channel_class
     *
     * @param channel_class the value for table_region_device.channel_class
     *
     * @mbggenerated
     */
    public void setChannel_class(String channel_class) {
        this.channel_class = channel_class == null ? null : channel_class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.channel_guid
     *
     * @return the value of table_region_device.channel_guid
     *
     * @mbggenerated
     */
    public String getChannel_guid() {
        return channel_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.channel_guid
     *
     * @param channel_guid the value for table_region_device.channel_guid
     *
     * @mbggenerated
     */
    public void setChannel_guid(String channel_guid) {
        this.channel_guid = channel_guid == null ? null : channel_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.channel_name
     *
     * @return the value of table_region_device.channel_name
     *
     * @mbggenerated
     */
    public String getChannel_name() {
        return channel_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.channel_name
     *
     * @param channel_name the value for table_region_device.channel_name
     *
     * @mbggenerated
     */
    public void setChannel_name(String channel_name) {
        this.channel_name = channel_name == null ? null : channel_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.channel_type
     *
     * @return the value of table_region_device.channel_type
     *
     * @mbggenerated
     */
    public String getChannel_type() {
        return channel_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.channel_type
     *
     * @param channel_type the value for table_region_device.channel_type
     *
     * @mbggenerated
     */
    public void setChannel_type(String channel_type) {
        this.channel_type = channel_type == null ? null : channel_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.channel_bit_num
     *
     * @return the value of table_region_device.channel_bit_num
     *
     * @mbggenerated
     */
    public String getChannel_bit_num() {
        return channel_bit_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.channel_bit_num
     *
     * @param channel_bit_num the value for table_region_device.channel_bit_num
     *
     * @mbggenerated
     */
    public void setChannel_bit_num(String channel_bit_num) {
        this.channel_bit_num = channel_bit_num == null ? null : channel_bit_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region_device.account_id
     *
     * @return the value of table_region_device.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region_device.account_id
     *
     * @param account_id the value for table_region_device.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    @Override
    public String toString() {
        return "TableRegionDevice{" +
                "id='" + id + '\'' +
                ", region_device_guid='" + region_device_guid + '\'' +
                ", region_guid='" + region_guid + '\'' +
                ", region_addr='" + region_addr + '\'' +
                ", region_name='" + region_name + '\'' +
                ", table_device_guid='" + table_device_guid + '\'' +
                ", gateway_id='" + gateway_id + '\'' +
                ", device_addr='" + device_addr + '\'' +
                ", device_name='" + device_name + '\'' +
                ", channel_class='" + channel_class + '\'' +
                ", channel_guid='" + channel_guid + '\'' +
                ", channel_name='" + channel_name + '\'' +
                ", channel_type='" + channel_type + '\'' +
                ", channel_bit_num='" + channel_bit_num + '\'' +
                ", account_id='" + account_id + '\'' +
                '}';
    }


}