package com.iot.pojo;

public class TableControl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.control_guid
     *
     * @mbggenerated
     */
    private String control_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.ctrl_sqn_guid
     *
     * @mbggenerated
     */
    private String ctrl_sqn_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.main_table_name
     *
     * @mbggenerated
     */
    private String main_table_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.dcgs_guid
     *
     * @mbggenerated
     */
    private String dcgs_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.m_address
     *
     * @mbggenerated
     */
    private String m_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.channel_bit_num
     *
     * @mbggenerated
     */
    private String channel_bit_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.m_value
     *
     * @mbggenerated
     */
    private String m_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.m_delay
     *
     * @mbggenerated
     */
    private String m_delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_control.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.id
     *
     * @return the value of table_control.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.id
     *
     * @param id the value for table_control.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.control_guid
     *
     * @return the value of table_control.control_guid
     *
     * @mbggenerated
     */
    public String getControl_guid() {
        return control_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.control_guid
     *
     * @param control_guid the value for table_control.control_guid
     *
     * @mbggenerated
     */
    public void setControl_guid(String control_guid) {
        this.control_guid = control_guid == null ? null : control_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.ctrl_sqn_guid
     *
     * @return the value of table_control.ctrl_sqn_guid
     *
     * @mbggenerated
     */
    public String getCtrl_sqn_guid() {
        return ctrl_sqn_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.ctrl_sqn_guid
     *
     * @param ctrl_sqn_guid the value for table_control.ctrl_sqn_guid
     *
     * @mbggenerated
     */
    public void setCtrl_sqn_guid(String ctrl_sqn_guid) {
        this.ctrl_sqn_guid = ctrl_sqn_guid == null ? null : ctrl_sqn_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.main_table_name
     *
     * @return the value of table_control.main_table_name
     *
     * @mbggenerated
     */
    public String getMain_table_name() {
        return main_table_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.main_table_name
     *
     * @param main_table_name the value for table_control.main_table_name
     *
     * @mbggenerated
     */
    public void setMain_table_name(String main_table_name) {
        this.main_table_name = main_table_name == null ? null : main_table_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.dcgs_guid
     *
     * @return the value of table_control.dcgs_guid
     *
     * @mbggenerated
     */
    public String getDcgs_guid() {
        return dcgs_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.dcgs_guid
     *
     * @param dcgs_guid the value for table_control.dcgs_guid
     *
     * @mbggenerated
     */
    public void setDcgs_guid(String dcgs_guid) {
        this.dcgs_guid = dcgs_guid == null ? null : dcgs_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.gateway_id
     *
     * @return the value of table_control.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.gateway_id
     *
     * @param gateway_id the value for table_control.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.m_address
     *
     * @return the value of table_control.m_address
     *
     * @mbggenerated
     */
    public String getM_address() {
        return m_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.m_address
     *
     * @param m_address the value for table_control.m_address
     *
     * @mbggenerated
     */
    public void setM_address(String m_address) {
        this.m_address = m_address == null ? null : m_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.channel_bit_num
     *
     * @return the value of table_control.channel_bit_num
     *
     * @mbggenerated
     */
    public String getChannel_bit_num() {
        return channel_bit_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.channel_bit_num
     *
     * @param channel_bit_num the value for table_control.channel_bit_num
     *
     * @mbggenerated
     */
    public void setChannel_bit_num(String channel_bit_num) {
        this.channel_bit_num = channel_bit_num == null ? null : channel_bit_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.m_value
     *
     * @return the value of table_control.m_value
     *
     * @mbggenerated
     */
    public String getM_value() {
        return m_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.m_value
     *
     * @param m_value the value for table_control.m_value
     *
     * @mbggenerated
     */
    public void setM_value(String m_value) {
        this.m_value = m_value == null ? null : m_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.m_delay
     *
     * @return the value of table_control.m_delay
     *
     * @mbggenerated
     */
    public String getM_delay() {
        return m_delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.m_delay
     *
     * @param m_delay the value for table_control.m_delay
     *
     * @mbggenerated
     */
    public void setM_delay(String m_delay) {
        this.m_delay = m_delay == null ? null : m_delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_control.account_id
     *
     * @return the value of table_control.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_control.account_id
     *
     * @param account_id the value for table_control.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}