package com.iot.pojo;

public class TableCtrlSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_ctrl_sequence.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_ctrl_sequence.ctrl_sqn_guid
     *
     * @mbggenerated
     */
    private String ctrl_sqn_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_ctrl_sequence.cdts_list_guid
     *
     * @mbggenerated
     */
    private String cdts_list_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_ctrl_sequence.control_number
     *
     * @mbggenerated
     */
    private String control_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_ctrl_sequence.control_time
     *
     * @mbggenerated
     */
    private String control_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_ctrl_sequence.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_ctrl_sequence.id
     *
     * @return the value of table_ctrl_sequence.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_ctrl_sequence.id
     *
     * @param id the value for table_ctrl_sequence.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_ctrl_sequence.ctrl_sqn_guid
     *
     * @return the value of table_ctrl_sequence.ctrl_sqn_guid
     *
     * @mbggenerated
     */
    public String getCtrl_sqn_guid() {
        return ctrl_sqn_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_ctrl_sequence.ctrl_sqn_guid
     *
     * @param ctrl_sqn_guid the value for table_ctrl_sequence.ctrl_sqn_guid
     *
     * @mbggenerated
     */
    public void setCtrl_sqn_guid(String ctrl_sqn_guid) {
        this.ctrl_sqn_guid = ctrl_sqn_guid == null ? null : ctrl_sqn_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_ctrl_sequence.cdts_list_guid
     *
     * @return the value of table_ctrl_sequence.cdts_list_guid
     *
     * @mbggenerated
     */
    public String getCdts_list_guid() {
        return cdts_list_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_ctrl_sequence.cdts_list_guid
     *
     * @param cdts_list_guid the value for table_ctrl_sequence.cdts_list_guid
     *
     * @mbggenerated
     */
    public void setCdts_list_guid(String cdts_list_guid) {
        this.cdts_list_guid = cdts_list_guid == null ? null : cdts_list_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_ctrl_sequence.control_number
     *
     * @return the value of table_ctrl_sequence.control_number
     *
     * @mbggenerated
     */
    public String getControl_number() {
        return control_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_ctrl_sequence.control_number
     *
     * @param control_number the value for table_ctrl_sequence.control_number
     *
     * @mbggenerated
     */
    public void setControl_number(String control_number) {
        this.control_number = control_number == null ? null : control_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_ctrl_sequence.control_time
     *
     * @return the value of table_ctrl_sequence.control_time
     *
     * @mbggenerated
     */
    public String getControl_time() {
        return control_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_ctrl_sequence.control_time
     *
     * @param control_time the value for table_ctrl_sequence.control_time
     *
     * @mbggenerated
     */
    public void setControl_time(String control_time) {
        this.control_time = control_time == null ? null : control_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_ctrl_sequence.account_id
     *
     * @return the value of table_ctrl_sequence.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_ctrl_sequence.account_id
     *
     * @param account_id the value for table_ctrl_sequence.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}