package com.iot.pojo;

public class TableRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.region_guid
     *
     * @mbggenerated
     */
    private String region_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.region_addr
     *
     * @mbggenerated
     */
    private String region_addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.region_name
     *
     * @mbggenerated
     */
    private String region_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.region_switch
     *
     * @mbggenerated
     */
    private String region_switch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.region_value
     *
     * @mbggenerated
     */
    private String region_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.region_delay
     *
     * @mbggenerated
     */
    private String region_delay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_region.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    private String status;

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.id
     *
     * @return the value of table_region.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.id
     *
     * @param id the value for table_region.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.region_guid
     *
     * @return the value of table_region.region_guid
     *
     * @mbggenerated
     */
    public String getRegion_guid() {
        return region_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.region_guid
     *
     * @param region_guid the value for table_region.region_guid
     *
     * @mbggenerated
     */
    public void setRegion_guid(String region_guid) {
        this.region_guid = region_guid == null ? null : region_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.region_addr
     *
     * @return the value of table_region.region_addr
     *
     * @mbggenerated
     */
    public String getRegion_addr() {
        return region_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.region_addr
     *
     * @param region_addr the value for table_region.region_addr
     *
     * @mbggenerated
     */
    public void setRegion_addr(String region_addr) {
        this.region_addr = region_addr == null ? null : region_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.region_name
     *
     * @return the value of table_region.region_name
     *
     * @mbggenerated
     */
    public String getRegion_name() {
        return region_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.region_name
     *
     * @param region_name the value for table_region.region_name
     *
     * @mbggenerated
     */
    public void setRegion_name(String region_name) {
        this.region_name = region_name == null ? null : region_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.region_switch
     *
     * @return the value of table_region.region_switch
     *
     * @mbggenerated
     */
    public String getRegion_switch() {
        return region_switch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.region_switch
     *
     * @param region_switch the value for table_region.region_switch
     *
     * @mbggenerated
     */
    public void setRegion_switch(String region_switch) {
        this.region_switch = region_switch == null ? null : region_switch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.region_value
     *
     * @return the value of table_region.region_value
     *
     * @mbggenerated
     */
    public String getRegion_value() {
        return region_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.region_value
     *
     * @param region_value the value for table_region.region_value
     *
     * @mbggenerated
     */
    public void setRegion_value(String region_value) {
        this.region_value = region_value == null ? null : region_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.region_delay
     *
     * @return the value of table_region.region_delay
     *
     * @mbggenerated
     */
    public String getRegion_delay() {
        return region_delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.region_delay
     *
     * @param region_delay the value for table_region.region_delay
     *
     * @mbggenerated
     */
    public void setRegion_delay(String region_delay) {
        this.region_delay = region_delay == null ? null : region_delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.gateway_id
     *
     * @return the value of table_region.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.gateway_id
     *
     * @param gateway_id the value for table_region.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_region.account_id
     *
     * @return the value of table_region.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_region.account_id
     *
     * @param account_id the value for table_region.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}