package com.iot.pojo;

public class TableSensorRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.record_guid
     *
     * @mbggenerated
     */
    private String record_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.table_device_guid
     *
     * @mbggenerated
     */
    private String table_device_guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.record_time
     *
     * @mbggenerated
     */
    private String record_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.air_Temperature
     *
     * @mbggenerated
     */
    private String air_Temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.air_Humidity
     *
     * @mbggenerated
     */
    private String air_Humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.substrate_Temperature
     *
     * @mbggenerated
     */
    private String substrate_Temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.substrate_Humidity
     *
     * @mbggenerated
     */
    private String substrate_Humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.substrate_PH
     *
     * @mbggenerated
     */
    private String substrate_PH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.carbon_Dioxide
     *
     * @mbggenerated
     */
    private String carbon_Dioxide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.illuminance
     *
     * @mbggenerated
     */
    private String illuminance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.substrate_Conductivity
     *
     * @mbggenerated
     */
    private String substrate_Conductivity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.ppfd
     *
     * @mbggenerated
     */
    private String ppfd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.liquid_PH
     *
     * @mbggenerated
     */
    private String liquid_PH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.lai
     *
     * @mbggenerated
     */
    private String lai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.liquid_Conductivity
     *
     * @mbggenerated
     */
    private String liquid_Conductivity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.liquid_DOC
     *
     * @mbggenerated
     */
    private String liquid_DOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.substrate_DOC
     *
     * @mbggenerated
     */
    private String substrate_DOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.reserve01
     *
     * @mbggenerated
     */
    private String reserve01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.reserve02
     *
     * @mbggenerated
     */
    private String reserve02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_sensor_record.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.id
     *
     * @return the value of table_sensor_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.id
     *
     * @param id the value for table_sensor_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.record_guid
     *
     * @return the value of table_sensor_record.record_guid
     *
     * @mbggenerated
     */
    public String getRecord_guid() {
        return record_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.record_guid
     *
     * @param record_guid the value for table_sensor_record.record_guid
     *
     * @mbggenerated
     */
    public void setRecord_guid(String record_guid) {
        this.record_guid = record_guid == null ? null : record_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.table_device_guid
     *
     * @return the value of table_sensor_record.table_device_guid
     *
     * @mbggenerated
     */
    public String getTable_device_guid() {
        return table_device_guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.table_device_guid
     *
     * @param table_device_guid the value for table_sensor_record.table_device_guid
     *
     * @mbggenerated
     */
    public void setTable_device_guid(String table_device_guid) {
        this.table_device_guid = table_device_guid == null ? null : table_device_guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.record_time
     *
     * @return the value of table_sensor_record.record_time
     *
     * @mbggenerated
     */
    public String getRecord_time() {
        return record_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.record_time
     *
     * @param record_time the value for table_sensor_record.record_time
     *
     * @mbggenerated
     */
    public void setRecord_time(String record_time) {
        this.record_time = record_time == null ? null : record_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.air_Temperature
     *
     * @return the value of table_sensor_record.air_Temperature
     *
     * @mbggenerated
     */
    public String getAir_Temperature() {
        return air_Temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.air_Temperature
     *
     * @param air_Temperature the value for table_sensor_record.air_Temperature
     *
     * @mbggenerated
     */
    public void setAir_Temperature(String air_Temperature) {
        this.air_Temperature = air_Temperature == null ? null : air_Temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.air_Humidity
     *
     * @return the value of table_sensor_record.air_Humidity
     *
     * @mbggenerated
     */
    public String getAir_Humidity() {
        return air_Humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.air_Humidity
     *
     * @param air_Humidity the value for table_sensor_record.air_Humidity
     *
     * @mbggenerated
     */
    public void setAir_Humidity(String air_Humidity) {
        this.air_Humidity = air_Humidity == null ? null : air_Humidity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.substrate_Temperature
     *
     * @return the value of table_sensor_record.substrate_Temperature
     *
     * @mbggenerated
     */
    public String getSubstrate_Temperature() {
        return substrate_Temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.substrate_Temperature
     *
     * @param substrate_Temperature the value for table_sensor_record.substrate_Temperature
     *
     * @mbggenerated
     */
    public void setSubstrate_Temperature(String substrate_Temperature) {
        this.substrate_Temperature = substrate_Temperature == null ? null : substrate_Temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.substrate_Humidity
     *
     * @return the value of table_sensor_record.substrate_Humidity
     *
     * @mbggenerated
     */
    public String getSubstrate_Humidity() {
        return substrate_Humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.substrate_Humidity
     *
     * @param substrate_Humidity the value for table_sensor_record.substrate_Humidity
     *
     * @mbggenerated
     */
    public void setSubstrate_Humidity(String substrate_Humidity) {
        this.substrate_Humidity = substrate_Humidity == null ? null : substrate_Humidity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.substrate_PH
     *
     * @return the value of table_sensor_record.substrate_PH
     *
     * @mbggenerated
     */
    public String getSubstrate_PH() {
        return substrate_PH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.substrate_PH
     *
     * @param substrate_PH the value for table_sensor_record.substrate_PH
     *
     * @mbggenerated
     */
    public void setSubstrate_PH(String substrate_PH) {
        this.substrate_PH = substrate_PH == null ? null : substrate_PH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.carbon_Dioxide
     *
     * @return the value of table_sensor_record.carbon_Dioxide
     *
     * @mbggenerated
     */
    public String getCarbon_Dioxide() {
        return carbon_Dioxide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.carbon_Dioxide
     *
     * @param carbon_Dioxide the value for table_sensor_record.carbon_Dioxide
     *
     * @mbggenerated
     */
    public void setCarbon_Dioxide(String carbon_Dioxide) {
        this.carbon_Dioxide = carbon_Dioxide == null ? null : carbon_Dioxide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.illuminance
     *
     * @return the value of table_sensor_record.illuminance
     *
     * @mbggenerated
     */
    public String getIlluminance() {
        return illuminance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.illuminance
     *
     * @param illuminance the value for table_sensor_record.illuminance
     *
     * @mbggenerated
     */
    public void setIlluminance(String illuminance) {
        this.illuminance = illuminance == null ? null : illuminance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.substrate_Conductivity
     *
     * @return the value of table_sensor_record.substrate_Conductivity
     *
     * @mbggenerated
     */
    public String getSubstrate_Conductivity() {
        return substrate_Conductivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.substrate_Conductivity
     *
     * @param substrate_Conductivity the value for table_sensor_record.substrate_Conductivity
     *
     * @mbggenerated
     */
    public void setSubstrate_Conductivity(String substrate_Conductivity) {
        this.substrate_Conductivity = substrate_Conductivity == null ? null : substrate_Conductivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.ppfd
     *
     * @return the value of table_sensor_record.ppfd
     *
     * @mbggenerated
     */
    public String getPpfd() {
        return ppfd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.ppfd
     *
     * @param ppfd the value for table_sensor_record.ppfd
     *
     * @mbggenerated
     */
    public void setPpfd(String ppfd) {
        this.ppfd = ppfd == null ? null : ppfd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.liquid_PH
     *
     * @return the value of table_sensor_record.liquid_PH
     *
     * @mbggenerated
     */
    public String getLiquid_PH() {
        return liquid_PH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.liquid_PH
     *
     * @param liquid_PH the value for table_sensor_record.liquid_PH
     *
     * @mbggenerated
     */
    public void setLiquid_PH(String liquid_PH) {
        this.liquid_PH = liquid_PH == null ? null : liquid_PH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.lai
     *
     * @return the value of table_sensor_record.lai
     *
     * @mbggenerated
     */
    public String getLai() {
        return lai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.lai
     *
     * @param lai the value for table_sensor_record.lai
     *
     * @mbggenerated
     */
    public void setLai(String lai) {
        this.lai = lai == null ? null : lai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.liquid_Conductivity
     *
     * @return the value of table_sensor_record.liquid_Conductivity
     *
     * @mbggenerated
     */
    public String getLiquid_Conductivity() {
        return liquid_Conductivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.liquid_Conductivity
     *
     * @param liquid_Conductivity the value for table_sensor_record.liquid_Conductivity
     *
     * @mbggenerated
     */
    public void setLiquid_Conductivity(String liquid_Conductivity) {
        this.liquid_Conductivity = liquid_Conductivity == null ? null : liquid_Conductivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.liquid_DOC
     *
     * @return the value of table_sensor_record.liquid_DOC
     *
     * @mbggenerated
     */
    public String getLiquid_DOC() {
        return liquid_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.liquid_DOC
     *
     * @param liquid_DOC the value for table_sensor_record.liquid_DOC
     *
     * @mbggenerated
     */
    public void setLiquid_DOC(String liquid_DOC) {
        this.liquid_DOC = liquid_DOC == null ? null : liquid_DOC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.substrate_DOC
     *
     * @return the value of table_sensor_record.substrate_DOC
     *
     * @mbggenerated
     */
    public String getSubstrate_DOC() {
        return substrate_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.substrate_DOC
     *
     * @param substrate_DOC the value for table_sensor_record.substrate_DOC
     *
     * @mbggenerated
     */
    public void setSubstrate_DOC(String substrate_DOC) {
        this.substrate_DOC = substrate_DOC == null ? null : substrate_DOC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.reserve01
     *
     * @return the value of table_sensor_record.reserve01
     *
     * @mbggenerated
     */
    public String getReserve01() {
        return reserve01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.reserve01
     *
     * @param reserve01 the value for table_sensor_record.reserve01
     *
     * @mbggenerated
     */
    public void setReserve01(String reserve01) {
        this.reserve01 = reserve01 == null ? null : reserve01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.reserve02
     *
     * @return the value of table_sensor_record.reserve02
     *
     * @mbggenerated
     */
    public String getReserve02() {
        return reserve02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.reserve02
     *
     * @param reserve02 the value for table_sensor_record.reserve02
     *
     * @mbggenerated
     */
    public void setReserve02(String reserve02) {
        this.reserve02 = reserve02 == null ? null : reserve02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_sensor_record.account_id
     *
     * @return the value of table_sensor_record.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_sensor_record.account_id
     *
     * @param account_id the value for table_sensor_record.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }
}