package com.iot.pojo;

import java.security.PrivateKey;

public class UserTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_id
     *
     * @mbggenerated
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_name
     *
     * @mbggenerated
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.e_mail
     *
     * @mbggenerated
     */
    private String e_mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.phone
     *
     * @mbggenerated
     */

    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.user_authorization
     *
     * @mbggenerated
     */
    private String user_authorization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.father_user
     *
     * @mbggenerated
     */
    private String father_user;

    private  String country;

    public  String getCountry(){
        return country;
    }
    public void setCountry(String country){
        this.country=country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_id
     *
     * @return the value of user_table.user_id
     *
     * @mbggenerated
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_id
     *
     * @param user_id the value for user_table.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_name
     *
     * @return the value of user_table.user_name
     *
     * @mbggenerated
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_name
     *
     * @param user_name the value for user_table.user_name
     *
     * @mbggenerated
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.password
     *
     * @return the value of user_table.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.password
     *
     * @param password the value for user_table.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.e_mail
     *
     * @return the value of user_table.e_mail
     *
     * @mbggenerated
     */
    public String getE_mail() {
        return e_mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.e_mail
     *
     * @param e_mail the value for user_table.e_mail
     *
     * @mbggenerated
     */
    public void setE_mail(String e_mail) {
        this.e_mail = e_mail == null ? null : e_mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.phone
     *
     * @return the value of user_table.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.phone
     *
     * @param phone the value for user_table.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.user_authorization
     *
     * @return the value of user_table.user_authorization
     *
     * @mbggenerated
     */
    public String getUser_authorization() {
        return user_authorization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.user_authorization
     *
     * @param user_authorization the value for user_table.user_authorization
     *
     * @mbggenerated
     */
    public void setUser_authorization(String user_authorization) {
        this.user_authorization = user_authorization == null ? null : user_authorization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.father_user
     *
     * @return the value of user_table.father_user
     *
     * @mbggenerated
     */
    public String getFather_user() {
        return father_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.father_user
     *
     * @param father_user the value for user_table.father_user
     *
     * @mbggenerated
     */
    public void setFather_user(String father_user) {
        this.father_user = father_user == null ? null : father_user.trim();
    }


    @Override
    public String toString() {
        return "UserTable{" +
                "user_id='" + user_id + '\'' +
                ", user_name='" + user_name + '\'' +
                ", password='" + password + '\'' +
                ", e_mail='" + e_mail + '\'' +
                ", phone='" + phone + '\'' +
                ", user_authorization='" + user_authorization + '\'' +
                ", father_user='" + father_user + '\'' +
                ", country='" + country + '\'' +
                '}';
    }
}