package com.iot.pojo;

public class UserGateway {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gateway.id
     *
     * @mbggenerated
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gateway.user_id
     *
     * @mbggenerated
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gateway.account_id
     *
     * @mbggenerated
     */
    private String account_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gateway.gateway_id
     *
     * @mbggenerated
     */
    private String gateway_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_gateway.id
     *
     * @return the value of user_gateway.id
     *
     * @mbggenerated
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_gateway.id
     *
     * @param id the value for user_gateway.id
     *
     * @mbggenerated
     */
    public void setId(int id) {
        this.id=id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_gateway.user_id
     *
     * @return the value of user_gateway.user_id
     *
     * @mbggenerated
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_gateway.user_id
     *
     * @param user_id the value for user_gateway.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_gateway.account_id
     *
     * @return the value of user_gateway.account_id
     *
     * @mbggenerated
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_gateway.account_id
     *
     * @param account_id the value for user_gateway.account_id
     *
     * @mbggenerated
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_gateway.gateway_id
     *
     * @return the value of user_gateway.gateway_id
     *
     * @mbggenerated
     */
    public String getGateway_id() {
        return gateway_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_gateway.gateway_id
     *
     * @param gateway_id the value for user_gateway.gateway_id
     *
     * @mbggenerated
     */
    public void setGateway_id(String gateway_id) {
        this.gateway_id = gateway_id == null ? null : gateway_id.trim();
    }
}