package com.iot.mapper;

import com.iot.pojo.AccountDataInfo;

import java.util.List;

public interface AccountDataInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_data_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_data_info
     *
     * @mbggenerated
     */
    int insert(AccountDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_data_info
     *
     * @mbggenerated
     */
    int insertSelective(AccountDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_data_info
     *
     * @mbggenerated
     */
    AccountDataInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_data_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountDataInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_data_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountDataInfo record);

    int deleteByNullGateway(String account_id);
    AccountDataInfo selectByAccountIdAndGatewayId(AccountDataInfo record);
    int updateByAccountIdAndGatewayId(AccountDataInfo accountDataInfo);
    List<AccountDataInfo> findAll();
    List<AccountDataInfo> selectByAccountId(String account_id);

}