package com.iot.mapper;

import com.iot.pojo.AppInfo;

public interface AppInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int insert(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbggenerated
     */
    int insertSelective(AppInfo record);
    AppInfo selectByappInfo(AppInfo record);
}