package com.iot.mapper;

import com.iot.pojo.DeviceClass;

public interface DeviceClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_class
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_class
     *
     * @mbggenerated
     */
    int insert(DeviceClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_class
     *
     * @mbggenerated
     */
    int insertSelective(DeviceClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_class
     *
     * @mbggenerated
     */
    DeviceClass selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceClass record);
}