package com.iot.mapper;

import com.iot.pojo.DeviceStandard;

public interface DeviceStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_standard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_standard
     *
     * @mbggenerated
     */
    int insert(DeviceStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_standard
     *
     * @mbggenerated
     */
    int insertSelective(DeviceStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_standard
     *
     * @mbggenerated
     */
    DeviceStandard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_standard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_standard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceStandard record);
}