package com.iot.mapper;

import com.iot.pojo.DispatcherLocation;

import java.util.List;

public interface DispatcherLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatcher_location
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatcher_location
     *
     * @mbggenerated
     */
    int insert(DispatcherLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatcher_location
     *
     * @mbggenerated
     */
    int insertSelective(DispatcherLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatcher_location
     *
     * @mbggenerated
     */
    DispatcherLocation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatcher_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DispatcherLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatcher_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DispatcherLocation record);

    int insertMany(List<DispatcherLocation> list);

    DispatcherLocation selectByGatewayId(String gatewayId);
    int delete(List<DispatcherLocation> list);
}