package com.iot.mapper;

import com.iot.pojo.PrivateRecipe;

import java.util.List;

public interface PrivateRecipeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String private_recipe_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe
     *
     * @mbggenerated
     */
    int insert(PrivateRecipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe
     *
     * @mbggenerated
     */
    int insertSelective(PrivateRecipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe
     *
     * @mbggenerated
     */
    PrivateRecipe selectByPrimaryKey(String private_recipe_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrivateRecipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrivateRecipe record);

    PrivateRecipe selectRecipeOne(PrivateRecipe record);

    List<PrivateRecipe> selectPrivateRecipeByAccountId(String account_id);

    PrivateRecipe selectRecipeBycropNameAndAccountId(PrivateRecipe record);

    int  updateByPrimaryKeyAndAccountId(PrivateRecipe record);

    int deleteByPrivateRecipeIdAndAccountId(PrivateRecipe record);
}