package com.iot.mapper;

import com.iot.pojo.PrivateRecipeIndex;

import java.util.List;

public interface PrivateRecipeIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_index
     *
     * @mbggenerated
     */
    int insert(PrivateRecipeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_index
     *
     * @mbggenerated
     */
    int insertSelective(PrivateRecipeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_index
     *
     * @mbggenerated
     */
    PrivateRecipeIndex selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrivateRecipeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrivateRecipeIndex record);

    List<PrivateRecipeIndex> selectByRegionAndAccountIdAndPrivateRecipeId(PrivateRecipeIndex record);
    List<PrivateRecipeIndex> selectByRegionAndAccountId(PrivateRecipeIndex record);
    PrivateRecipeIndex selectByPrivateRecipeIdAndAccountId(PrivateRecipeIndex rocord);
    List<PrivateRecipeIndex> selectByPrivateRecipeIdAndAccountIds(PrivateRecipeIndex rocord);
    int deleteByPrivatePrcipeIdAndAccountId(PrivateRecipeIndex record);
    int updateStartTimeByPrivateId(PrivateRecipeIndex record);

    int  deleteByPrivatePrcipeIdAndAccountIdAndRegionId(PrivateRecipeIndex record);
    int updateStatus(PrivateRecipeIndex record);
}