package com.iot.mapper;

import com.iot.pojo.PrivateRecipeData;

import java.util.LinkedList;
import java.util.List;

public interface PrivateRecipeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_data
     *
     * @mbggenerated
     */
    int insert(PrivateRecipeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_data
     *
     * @mbggenerated
     */
    int insertSelective(PrivateRecipeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_data
     *
     * @mbggenerated
     */
    PrivateRecipeData selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrivateRecipeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_recipe_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrivateRecipeData record);
    List<PrivateRecipeData> selectRecipeDataAll();

    LinkedList<PrivateRecipeData> selectRecipeDataByprivateRecipeIdAndAccountId(PrivateRecipeData record);

    List<PrivateRecipeData> selectRecipeDataByprivateRecipeIdAndAccountIdAndDay(PrivateRecipeData record);
    int updateByPrimaryKeyAndAccountId(PrivateRecipeData record);

    int deleteByPrivateRecipeIdAndAccountId(PrivateRecipeData record);

    int deleteByPrimaryKeyAndDayAndAccountId(PrivateRecipeData record);

    int updateByPrivateRecipeIdAndAccountId(PrivateRecipeData record);

    List<PrivateRecipeData> selectRecipeDataByprivateRecipeIdAndAccountIdAndDayBig(PrivateRecipeData record);

    List<PrivateRecipeData> selectRecipeDataByprivateRecipeIdAndAccountIdAndDaymin(PrivateRecipeData record);
}