package com.iot.mapper;

import com.iot.pojo.PublicRecipeData;

import java.util.List;

public interface PublicRecipeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_recipe_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_recipe_data
     *
     * @mbggenerated
     */
    int insert(PublicRecipeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_recipe_data
     *
     * @mbggenerated
     */
    int insertSelective(PublicRecipeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_recipe_data
     *
     * @mbggenerated
     */
    PublicRecipeData selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_recipe_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PublicRecipeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_recipe_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PublicRecipeData record);

    List<PublicRecipeData> selectRecipeDataAll();

    PublicRecipeData selectUserRecipeDataDetil(String public_recipe_id);

    List<PublicRecipeData> selectBypublicRecipeId(String public_recipe_id);
}