package com.iot.mapper;

import com.iot.pojo.PublicRecipe;

import java.util.List;

public interface PublicRecipeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_recipe
     *
     * @mbggenerated
     */
    int insert(PublicRecipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_recipe
     *
     * @mbggenerated
     */
    int insertSelective(PublicRecipe record);

    List<PublicRecipe> selectRecipesByAll();
    PublicRecipe selectRecipeOne(String public_recipe_id);

}