package com.iot.mapper;

import com.iot.pojo.RegionStatus;

public interface RegionStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String region_guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_status
     *
     * @mbggenerated
     */
    int insert(RegionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_status
     *
     * @mbggenerated
     */
    int insertSelective(RegionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_status
     *
     * @mbggenerated
     */
    RegionStatus selectByPrimaryKey(String region_guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RegionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RegionStatus record);
}