package com.iot.mapper;

import com.iot.pojo.TableGroup;

import java.util.List;

public interface TableGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group
     *
     * @mbggenerated
     */
    int insert(TableGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group
     *
     * @mbggenerated
     */
    int insertSelective(TableGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group
     *
     * @mbggenerated
     */
    TableGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableGroup record);

    int updateByGroup_guidAndAccount_id(TableGroup record);

    List<TableGroup> selectGroup (TableGroup record);

    int updateByAccountId(TableGroup record);

    int deleteByAccountIdAndGroupId(TableGroup record);

    int updateByGroup_guidAndAccount_idAndGateway_id(TableGroup record);

    int deleteByAccountIdAndGroupaddrAndGateway_id(TableGroup record);

    int updateByGroup_addrAndAccount_idAndGateway_id(TableGroup record);

    TableGroup  selectByGroupGuidAndAccountIdAndGatewayId(TableGroup record);

}