package com.iot.mapper;

import com.iot.pojo.TableRegionCdtsCtrl;

import java.util.List;

public interface TableRegionCdtsCtrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_cdts_ctrl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_cdts_ctrl
     *
     * @mbggenerated
     */
    int insert(TableRegionCdtsCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_cdts_ctrl
     *
     * @mbggenerated
     */
    int insertSelective(TableRegionCdtsCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_cdts_ctrl
     *
     * @mbggenerated
     */
    TableRegionCdtsCtrl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_cdts_ctrl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableRegionCdtsCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_cdts_ctrl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableRegionCdtsCtrl record);

    //
    List<TableRegionCdtsCtrl> selectByAccoutIdAndGatewayIdAndRegionGuid(TableRegionCdtsCtrl record);

    int updateRegionNameByAccountIdAndGatewayIdAndRegionGuid(TableRegionCdtsCtrl record);

    int deleteByRegionGuidAndAccountIdAndGatewayId(TableRegionCdtsCtrl record);
}