package com.iot.mapper;

import com.iot.pojo.TableChannel;

import java.util.List;

public interface TableChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_channel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_channel
     *
     * @mbggenerated
     */
    int insert(TableChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_channel
     *
     * @mbggenerated
     */
    int insertSelective(TableChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_channel
     *
     * @mbggenerated
     */
    TableChannel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableChannel record);


    List<TableChannel> selectByDeviceGuid(TableChannel record);

    List<TableChannel> selectByDevice_idAndAccout_idAndGateway_id(TableChannel record);


    List<TableChannel> selectChannelInfo(TableChannel record);



    List<TableChannel> selectByDevice_guidAndAccout_idAndGateway_id(TableChannel record);

    List<TableChannel> selectByDeviceGuidAndAccountId(TableChannel record);

    TableChannel selectByDeselectByChannelGuidAndAccount_idAndGateway_id(TableChannel record);

}