package com.iot.mapper;

import com.iot.pojo.TableDcgsRecord;

public interface TableDcgsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dcgs_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dcgs_record
     *
     * @mbggenerated
     */
    int insert(TableDcgsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dcgs_record
     *
     * @mbggenerated
     */
    int insertSelective(TableDcgsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dcgs_record
     *
     * @mbggenerated
     */
    TableDcgsRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dcgs_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableDcgsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dcgs_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableDcgsRecord record);
}