package com.iot.mapper;

import com.iot.pojo.TableGroup;
import com.iot.pojo.TableGroupMembers;

import java.util.List;

public interface TableGroupMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group_members
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group_members
     *
     * @mbggenerated
     */
    int insert(TableGroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group_members
     *
     * @mbggenerated
     */
    int insertSelective(TableGroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group_members
     *
     * @mbggenerated
     */
    TableGroupMembers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group_members
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableGroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_group_members
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableGroupMembers record);

    int deleteByAccountIdAndDeviceGuid(TableGroupMembers record);
    int updateByAccountIdAndGroupMemberGuid(TableGroupMembers record);

    List<TableGroupMembers> selectGroupMember(TableGroupMembers record);

    int deleteByAccountIdAndGroup_GuidAndGroup_addr(TableGroupMembers record);

    List<TableGroupMembers> selectByDevice_guidAndGroup_guid(TableGroupMembers record);

    List<TableGroupMembers> selectByGroupGuid(String group_guid);

    List<TableGroupMembers>  selectByGroupGuidAndAccount_idAndGateway_id(TableGroupMembers record);

    int deleteByAccountIdAndDeviceGuidAndGroup_guid(TableGroupMembers record);

    List<TableGroupMembers> selectByGroupAddrAndAccount_idAndGateway_id(TableGroupMembers record);

    int deleteByAccountIdAndGatewayAndGroup_addr(TableGroupMembers record);

    int deleteByAccountIdAndDeviceaddrAndGroup_addrAndGatewayId(TableGroupMembers record);

    List<TableGroupMembers> findGroupMemberByGroupAddr(TableGroupMembers record);

    TableGroupMembers selectByDevice_guidAndGroup_guidAndAccountIdAndGatewayId(TableGroupMembers record);

    TableGroupMembers selectByGroupMembersGuidAndAccount_idAndGateway_id(TableGroupMembers record);

    List<TableGroupMembers> selectByGroupGuidAndAccount_idAndGateway_idAndDeviceGuid(TableGroupMembers record);

   List<TableGroupMembers> selectDeviceGuidAndGatewayIdAndAccountId(TableGroupMembers tableGroupMembers);

    int updateByDeviceGuidAndGatewayIdAndAccountId(TableGroupMembers tableGroupMembers);
}