package com.iot.mapper;

import com.iot.pojo.TableControlRecord;

public interface TableControlRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control_record
     *
     * @mbggenerated
     */
    int insert(TableControlRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control_record
     *
     * @mbggenerated
     */
    int insertSelective(TableControlRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control_record
     *
     * @mbggenerated
     */
    TableControlRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableControlRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableControlRecord record);
}