package com.iot.mapper;

import com.iot.pojo.TableScene;

import java.util.List;

public interface TableSceneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene
     *
     * @mbggenerated
     */
    int insert(TableScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene
     *
     * @mbggenerated
     */
    int insertSelective(TableScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene
     *
     * @mbggenerated
     */
    TableScene selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableScene record);

    List<TableScene> selectScene(TableScene record);

    int updateByAccountIdAndSceneGuid(TableScene record);

    int deleteByAccountIdAndSceneGuid(TableScene record);

    int deleteByAccountIdAndSceneaddrAndGatewayId(TableScene record);

    int updateByAccountIdAndSceneGuidAndGatewayId(TableScene record);

    int updateByAccountIdAndSceneaddrAndGatewayId(TableScene record);

    List<TableScene> selectSceneAccount_idAndGateway_idAndSceneGuid(TableScene record);
}