package com.iot.mapper;

import com.iot.pojo.TableSensorRecord;

import java.util.List;
import java.util.Map;

public interface TableSensorRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_sensor_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_sensor_record
     *
     * @mbggenerated
     */
    int insert(TableSensorRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_sensor_record
     *
     * @mbggenerated
     */
    int insertSelective(TableSensorRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_sensor_record
     *
     * @mbggenerated
     */
    TableSensorRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_sensor_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableSensorRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_sensor_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableSensorRecord record);

    int insertMany(List<TableSensorRecord> list);

    List<TableSensorRecord>getNowSenorData(Map map);
    List<TableSensorRecord> getSenorData(Map map);

    List<TableSensorRecord> selectLimitData(Map<String,Integer> map);
    int getAllRecordNumber(Map<String,String> map);

    List<TableSensorRecord> selectDailyData(Map<String,String> map);


    void updateRecordTime(List<TableSensorRecord>list);

    TableSensorRecord getNowSenorDataMinTime(Map map);
}