package com.iot.mapper;

import com.iot.pojo.TableRegion;

import java.util.List;

public interface TableRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region
     *
     * @mbggenerated
     */
    int insert(TableRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region
     *
     * @mbggenerated
     */
    int insertSelective(TableRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region
     *
     * @mbggenerated
     */
    TableRegion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableRegion record);

    TableRegion selectByRegionGuid(String guid);

    int addRegion(TableRegion record);
    List<TableRegion> selectByGatewayId(TableRegion record);


    /*
    jim
     */
    int  updateByUidAndAccountId(TableRegion record);

    int deleteByUidAndAccountId(TableRegion record);

    List<TableRegion> selectByGatewayIdAndAcountId(TableRegion record);

    TableRegion selectRegionValue(TableRegion record);


    int mysqlControll(TableRegion record);

    int updateByUidAndAccountIdAndGatewayID(TableRegion tableRegion);

    int deleteByRegion_addrAndAccountIdAndGateway_id(TableRegion record);

    List<TableRegion> selectAccount_id(TableRegion record);

    TableRegion selectByRegionGuidAndGateway_idAndAccount_id(TableRegion record);

    TableRegion selectByRegionGuidAndGateway_idAndAccount_idas(TableRegion record);

}