package com.iot.mapper;

import com.iot.pojo.TableRegionScene;

import java.util.List;

public interface TableRegionSceneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_scene
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_scene
     *
     * @mbggenerated
     */
    int insert(TableRegionScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_scene
     *
     * @mbggenerated
     */
    int insertSelective(TableRegionScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_scene
     *
     * @mbggenerated
     */
    TableRegionScene selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_scene
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableRegionScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_scene
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableRegionScene record);

    TableRegionScene findRegionSceneByAccountIdAndSceneId(TableRegionScene record);

    int updateByAccountIdAndSceneGuid(TableRegionScene record);

    List<TableRegionScene> findRegionSceneByAccountIdAndRegionId(TableRegionScene record);
    int deleteScene(TableRegionScene record);

    int updateByAccountIdAndTableSceneGuid(TableRegionScene record);

    TableRegionScene findRegionSceneByAccountIdAndSceneIdAndGatewayId(TableRegionScene record);

    TableRegionScene findRegionSceneByAccountIdAndSceneaddrAndGatewayId(TableRegionScene record);

    int deleteSceneBySence_addrAndGateway_idAndAccount_id(TableRegionScene record);

    TableRegionScene findRegionSceneByAccountIdAndSceneguidAndGatewayId(TableRegionScene record);

    int updateByAccountIdAndTableSceneGuidAndGatewayId(TableRegionScene record);

    List<TableRegionScene> findRegionSceneByAccountIdAndRegionguidAndGatewayId(TableRegionScene record);

    int deleteRegionSceneByRegionGuidAndGateway_idAndAccount_id(TableRegionScene record);

    TableRegionScene findRegionSceneByAccountIdAndSceneguidAndGatewayIdAndRegionGuid(TableRegionScene record);

}