package com.iot.mapper;

import com.iot.pojo.TableRegister;

public interface TableRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_register
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_register
     *
     * @mbggenerated
     */
    int insert(TableRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_register
     *
     * @mbggenerated
     */
    int insertSelective(TableRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_register
     *
     * @mbggenerated
     */
    TableRegister selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_register
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_register
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableRegister record);
}