package com.iot.mapper;

import com.iot.pojo.TableRegion;
import com.iot.pojo.TableRegionDevice;

import java.util.List;
import java.util.Map;

public interface TableRegionDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_device
     *
     * @mbggenerated
     */
    int insert(TableRegionDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_device
     *
     * @mbggenerated
     */
    int insertSelective(TableRegionDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_device
     *
     * @mbggenerated
     */
    TableRegionDevice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableRegionDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_region_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableRegionDevice record);


    List<TableRegionDevice> selectByAccountIdAndRegiongGuid(TableRegionDevice tableRegionDevice);

    List<Map> selectByAccountIdAndRegiongGuidaa(TableRegionDevice tableRegionDevice);

    List<TableRegionDevice> selectByAccountIdAndDrvice_guid(TableRegionDevice tableRegionDevice);


    int deleteByAccountIdAndDeviceGuid(TableRegionDevice tableRegionDevice);


    int deleteByRegion_AddrIdAndDevice_Addr(TableRegionDevice tableRegionDevice);

    int deleteByRegion_guidAndAccount_id(TableRegionDevice tableRegionDevice);

    int deleteByRegion_guidAndAccount_idGateway_id(TableRegionDevice tableRegionDevice);

    List<TableRegionDevice>  selectByAccountIdAndRegiongGuidGateway_id(TableRegionDevice tableRegionDevice);

    List<TableRegionDevice> selectByAccountIdAndDrvice_guidRegion_guid(TableRegionDevice tableRegionDevice);

    int updateByRagion_guidAndDrvice_guidAccount_id(TableRegionDevice tableRegionDevice);

    List<TableRegionDevice> selectByAccountIdAndRegiongaddrAndGateway_id(TableRegionDevice tableRegionDevice);

    int deleteByRegion_addrAndAccount_idGateway_id(TableRegionDevice tableRegionDevice);

    List<Map> selectByAccountIdAndRegiongGuidAndgatewayid(TableRegionDevice tableRegionDevice);

    List<TableRegionDevice> getRegionSensors(TableRegionDevice tableRegionDevice);

    int updateRegionNameByAccountIdAndGatewayIdAndRegionId(TableRegionDevice tableRegionDevice);

    List<TableRegionDevice> getDisticRegionDevice(TableRegionDevice tableRegionDevice);

    TableRegionDevice selectByAccountIdAndRegiongDeviceGuidGateway_id(TableRegionDevice record);

    List<TableRegionDevice> selectByAccountIdAndRegiongGuidGateway_idAndDeviceGuid(TableRegionDevice record);

    List<TableRegionDevice> selectByAccountIdAndRegiongGuidGateway_idgroupByDeviceGuid(TableRegionDevice record);

    int updateByDrvice_guidAccount_idAndGatewayId(TableRegionDevice tableRegionDevice);

    List<TableRegionDevice> selectByAccountIdAndDrvice_guidAndGatewayId(TableRegionDevice tableRegionDevice);
}