package com.iot.mapper;

import com.iot.pojo.TableSceneMembers;

import java.util.List;

public interface TableSceneMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene_members
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene_members
     *
     * @mbggenerated
     */
    int insert(TableSceneMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene_members
     *
     * @mbggenerated
     */
    int insertSelective(TableSceneMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene_members
     *
     * @mbggenerated
     */
    TableSceneMembers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene_members
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableSceneMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_scene_members
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableSceneMembers record);
    int updateByAccountIdAndSceneMemberGuid(TableSceneMembers record);
    List<TableSceneMembers> selectSceneMember(TableSceneMembers record);
    int deleteByAccountIdAndDeviceGuid(TableSceneMembers record);

    List<TableSceneMembers> selectSceneMemberBySceneaddrAndGatewayIdAndAccountId(TableSceneMembers record);

    int deleteByAccountIdAndSenceaddrAndGatewayId(TableSceneMembers record);

    int  deleteByAccountIdAndSceneMembersGuidAndGatewayId(TableSceneMembers record);

    TableSceneMembers selectSceneMemberByDeviceguidAndGatewayIdAndAccountId(TableSceneMembers record);

    List<TableSceneMembers> selectSceneMemberByScene_guidAndGatewayIdAndAccountId(TableSceneMembers record);

    int deleteByAccountIdAndScene_addrAndGatewayIdAndDevice_addr(TableSceneMembers record);

    int updateByAccountIdAndSceneMemberGuidAndGatewayId(TableSceneMembers record);

    TableSceneMembers selectSceneMemberByDeviceguidAndGatewayIdAndAccountIdAndSceneGuid(TableSceneMembers record);

    TableSceneMembers selectSceneMemberBysceneMemberGuidAndGatewayIdAndAccountIdAnd(TableSceneMembers record);

    List<TableSceneMembers> selectSceneMemberByScene_guidAndGatewayIdAndAccountIdAndDeviceGuid(TableSceneMembers record);

    int updateByAccountIdAndDevice_guidAndGatewayId(TableSceneMembers tableSceneMembers);

    List<TableSceneMembers>selectSceneMemberByDeviceguidAndGatewayIdAndAccountIdList(TableSceneMembers tableSceneMembers);
}