package com.iot.mapper;

import com.iot.pojo.TableControl;

public interface TableControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control
     *
     * @mbggenerated
     */
    int insert(TableControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control
     *
     * @mbggenerated
     */
    int insertSelective(TableControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control
     *
     * @mbggenerated
     */
    TableControl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_control
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableControl record);
}