package com.iot.mapper;

import com.iot.pojo.TableConditons;

public interface TableConditonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_conditons
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_conditons
     *
     * @mbggenerated
     */
    int insert(TableConditons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_conditons
     *
     * @mbggenerated
     */
    int insertSelective(TableConditons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_conditons
     *
     * @mbggenerated
     */
    TableConditons selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_conditons
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableConditons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_conditons
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableConditons record);
}