package com.iot.mapper;

import com.iot.pojo.TableCtrlSequence;

public interface TableCtrlSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_ctrl_sequence
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_ctrl_sequence
     *
     * @mbggenerated
     */
    int insert(TableCtrlSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_ctrl_sequence
     *
     * @mbggenerated
     */
    int insertSelective(TableCtrlSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_ctrl_sequence
     *
     * @mbggenerated
     */
    TableCtrlSequence selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_ctrl_sequence
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableCtrlSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_ctrl_sequence
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableCtrlSequence record);
}