package com.iot.mapper;

import com.iot.pojo.TableCdtsList;

public interface TableCdtsListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_cdts_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_cdts_list
     *
     * @mbggenerated
     */
    int insert(TableCdtsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_cdts_list
     *
     * @mbggenerated
     */
    int insertSelective(TableCdtsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_cdts_list
     *
     * @mbggenerated
     */
    TableCdtsList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_cdts_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableCdtsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_cdts_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableCdtsList record);
}