package com.iot.mapper;

import com.iot.pojo.UserGateway;

import java.util.List;

public interface UserGatewayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gateway
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gateway
     *
     * @mbggenerated
     */
    int insert(UserGateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gateway
     *
     * @mbggenerated
     */
    int insertSelective(UserGateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gateway
     *
     * @mbggenerated
     */
    UserGateway selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gateway
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserGateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gateway
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserGateway record);

    List<UserGateway> selectByUserId(String userId);

    int deleteByUser_id(String user_id);
}